/**
 * Smoke 测试：E2E 数据种子脚本
 * 负责初始化 E2E 测试所需的最小数据集，确保环境一致性。
 * 包含：User, Organization, Project, NovelSource (with rawText)
 */

import { PrismaClient } from 'database';
import { randomBytes } from 'crypto';

const prisma = new PrismaClient({});

// 固定配置，保证多次运行幂等
const SEED_USER_EMAIL = 'e2e_seed_user@scu.test';
const SEED_USER_PASSWORD_HASH = 'seed-password-hash'; // 仅用于占位，实际登录可能走 bypass 或重置
const SEED_ORG_SLUG = 'e2e-seed-org';
const SEED_PROJECT_NAME = 'E2E Verify Project';
const SEED_NOVEL_TITLE = 'E2E Seed Novel';

async function main() {
  console.log('🌱 Starting E2E Data Seeding...');

  try {
    // 1. Upsert User
    const user = await prisma.user.upsert({
      where: { email: SEED_USER_EMAIL },
      update: {},
      create: {
        email: SEED_USER_EMAIL,
        passwordHash: SEED_USER_PASSWORD_HASH,
        // name: 'E2E Seed User', // User model has no name field in schema
      },
    });
    console.log(`✅ User ensured: ${user.id}`);

    // 2. Upsert Organization
    const org = await prisma.organization.upsert({
      where: { slug: SEED_ORG_SLUG },
      update: { ownerId: user.id },
      create: {
        name: 'E2E Seed Org',
        slug: SEED_ORG_SLUG,
        ownerId: user.id,
      },
    });
    console.log(`✅ Organization ensured: ${org.id}`);

    // 3. Ensure Membership
    await prisma.organizationMember.upsert({
      where: {
        userId_organizationId: {
          // Correct composite key name per schema @@unique([userId, organizationId])
          organizationId: org.id,
          userId: user.id,
        },
      },
      update: { role: 'OWNER' as any },
      create: {
        organizationId: org.id,
        userId: user.id,
        role: 'OWNER' as any,
      },
    });

    // 4. Update User Default Org
    await prisma.user.update({
      where: { id: user.id },
      data: { defaultOrganizationId: org.id },
    });

    // 5. Upsert Project
    // 我们通过 name + ownerId 来近似查找，或者如果能确定 ID 更好，但 Prisma 不支持 upsert where 非 unique
    // 这里先 findFirst，没有则 create
    let project = await prisma.project.findFirst({
      where: {
        ownerId: user.id,
        name: SEED_PROJECT_NAME,
        organizationId: org.id,
      },
    });

    if (!project) {
      project = await prisma.project.create({
        data: {
          name: SEED_PROJECT_NAME,
          ownerId: user.id,
          organizationId: org.id,
          description: 'Auto-generated by seed_e2e_data.ts',
        },
      });
      console.log(`✅ Project created: ${project.id}`);
    } else {
      console.log(`✅ Project found: ${project.id}`);
    }

    // 6. Upsert NovelSource (CRITICAL for Worker)
    // 查找该项目下的最新 NovelSource
    let novelSource = await prisma.novelSource.findFirst({
      where: { projectId: project.id },
      orderBy: { createdAt: 'desc' },
    });

    const rawTextContent = `
Chapter 1: The Seed.
This is a reliable text source for E2E testing.
It ensures the worker has something to parse.
No more "rawText empty" errors.
    `.trim();

    if (novelSource) {
      // 确保 rawText 存在
      await prisma.novelSource.update({
        where: { id: novelSource.id },
        data: {
          novelTitle: SEED_NOVEL_TITLE, // Field is novelTitle
          rawText: rawTextContent,
        },
      });
      console.log(`✅ NovelSource updated: ${novelSource.id}`);
    } else {
      novelSource = await prisma.novelSource.create({
        data: {
          projectId: project.id,
          novelTitle: SEED_NOVEL_TITLE, // Field is novelTitle
          novelAuthor: 'Seed Bot', // Field is novelAuthor
          rawText: rawTextContent,
          // sourceType: 'TEXT', // Not in schema? Schema shows fields are mostly optional strings. 'sourceType' is NOT in schema.
          // Schema has: fileType, etc. But no sourceType enum visible in Lines 1041-1064.
          // Removing sourceType to be safe.
        },
      });
      console.log(`✅ NovelSource created: ${novelSource.id}`);
    }

    // 7. Seed Key Hierarchy (Optional but good for completeness)
    const season = await prisma.season.upsert({
      where: { projectId_index: { projectId: project.id, index: 1 } },
      update: {},
      create: { projectId: project.id, index: 1, title: 'Seed S1' },
    });

    // Episode doesn't have a reliable unique composite key in some schema versions, check manually
    let episode = await prisma.episode.findFirst({
      where: { seasonId: season.id, index: 1 },
    });
    if (!episode) {
      episode = await prisma.episode.create({
        data: { seasonId: season.id, index: 1, name: 'Seed E1' },
      });
    }
    console.log(`✅ Hierarchy ensured (S1/E1) for context`);

    console.log('🎉 Seeding Complete!');
  } catch (error) {
    console.error('❌ Seeding Failed:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
