import type { Request, Response } from 'express';
import { raw, Router } from 'express';
import type {
  CreateAssetItemInput,
  CreateImportJobInput,
  CreateProjectInput,
  CreatePreviewVideoJobInput,
  CreateRenderJobInput,
  CreateStoredFileInput,
  CreateUploadSessionInput,
  GenerateEpisodeOutlineInput,
  ImportNovelInput,
  Project,
  UpdateRenderJobStatusInput,
  UploadChunkInput,
  SceneScript
} from '../../../packages/domain/src';
import { createId } from './id';
import {
  buildEpisodePackage,
  generateEpisodeOutline,
  generateScenes,
  generateShots,
  inferNovelTitleFromText,
  importNovel,
  reviewConsistency
} from './pipeline';
import { readStoredTextFile, storeProjectFile, storeProjectFileBuffer } from './file-storage';
import { createImportJob, markImportJobCompleted, markImportJobFailed, markImportJobRunning } from './import-jobs';
import { preparePreviewVideoJob } from './preview-video';
import { dispatchRenderJob } from './render-video';
import { projectRepository } from './repository-factory';
import { clearEpisodeOutputs, clearGeneratedOutputs, clearImportState } from './project-state';
import { appendVersion } from './versioning';

function now(): string {
  return new Date().toISOString();
}

async function getProjectOr404(projectId: string, res: Response) {
  const record = await projectRepository.get(projectId);
  if (!record) {
    res.status(404).json({ message: 'Project not found' });
    return undefined;
  }
  return record;
}

function applyBaselineEpisodePackage(record: Awaited<ReturnType<typeof projectRepository.get>>) {
  if (!record?.novel) {
    return;
  }

  const episodePackage = buildEpisodePackage(record.project.id, record.novel.title, record.novel.chapters, record.characters, {
    episodeNo: 1,
    adaptationMode: 'faithful',
    estimatedMinutes: 24
  });

  clearEpisodeOutputs(record, episodePackage.outline.episodeNo);
  record.episodeOutlines = record.episodeOutlines.concat(episodePackage.outline);
  record.scenes = record.scenes.concat(episodePackage.scenes);
  record.shots = record.shots.concat(episodePackage.shots);
  record.issues = episodePackage.issues;
  record.project.stage = 'reviewed';
  record.project.updatedAt = now();
  appendVersion(record, {
    stage: record.project.stage,
    action: 'episode_package_generated',
    summary: `生成第 ${episodePackage.outline.episodeNo} 集整包`,
    detail: `导入完成后已自动生成基础剧本产物：${episodePackage.scenes.length} 个分场、${episodePackage.shots.length} 个分镜、${episodePackage.issues.length} 条审查结果。`,
    metadata: {
      episodeNo: episodePackage.outline.episodeNo,
      sceneCount: episodePackage.scenes.length,
      shotCount: episodePackage.shots.length,
      issueCount: episodePackage.issues.length,
      autoGenerated: true
    }
  });
}

function isWeakTitle(title: string | undefined): boolean {
  const normalized = title?.trim() || '';
  return normalized === '' || ['未命名小说', '雨夜真相', '小说正文', '新建小说'].includes(normalized);
}

function isSuspiciousStoredFilename(name: string): boolean {
  const basename = name.replace(/\.[^.]+$/, '');
  return basename.length > 0 && /^[_?]+$/u.test(basename);
}

function recoverStoredFilename(name: string, title: string): string {
  const extension = name.match(/\.[^.]+$/)?.[0] || '.txt';
  return `${title}${extension}`;
}

function deriveTitleFromStoredFilename(name: string): string {
  return name.replace(/\.[^.]+$/, '').replace(/^[_?]+|[_?]+$/g, '').trim();
}

export function createRoutes(): Router {
  const router = Router();
  const uploadBodyLimit = process.env.ANIME_STUDIO_V2_UPLOAD_BODY_LIMIT || process.env.ANIME_STUDIO_V2_BODY_LIMIT || '256mb';

  router.get('/health', (_req, res) => {
    res.json({ ok: true, service: 'anime-studio-v2-api' });
  });

  router.get('/api/projects', async (_req, res) => {
    res.json(await projectRepository.list());
  });

  router.post('/api/projects', async (req: Request<unknown, unknown, CreateProjectInput>, res) => {
    const input = req.body;
    if (!input?.name?.trim()) {
      res.status(400).json({ message: 'name is required' });
      return;
    }

    const project: Project = {
      id: createId('project'),
      name: input.name.trim(),
      description: input.description?.trim(),
      stage: 'project_created',
      createdAt: now(),
      updatedAt: now()
    };

    const record = {
      project,
      characters: [],
      episodeOutlines: [],
      scenes: [],
      shots: [],
      issues: [],
      versions: [],
      previewJobs: [],
      renderJobs: [],
      uploadSessions: [],
      assets: [],
      storedFiles: [],
      importJobs: []
    };
    appendVersion(record, {
      stage: record.project.stage,
      action: 'project_initialized',
      summary: '项目已创建',
      detail: `项目「${record.project.name}」已建立，可开始导入长篇小说并进入动画化拆解。`
    });

    const createdRecord = await projectRepository.create(record);

    res.status(201).json(createdRecord);
  });

  router.get('/api/projects/:projectId', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }
    res.json(record);
  });

  router.get('/api/projects/:projectId/versions', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    res.json(record.versions);
  });

  router.get('/api/projects/:projectId/preview-jobs', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    res.json(record.previewJobs);
  });

  router.get('/api/projects/:projectId/render-jobs', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    res.json(record.renderJobs);
  });

  router.get('/api/projects/:projectId/upload-sessions', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    res.json(record.uploadSessions);
  });

  router.get('/api/projects/:projectId/assets', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    res.json(record.assets);
  });

  router.get('/api/projects/:projectId/files', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    res.json(record.storedFiles);
  });

  router.get('/api/projects/:projectId/import-jobs', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    res.json(record.importJobs);
  });

  router.post(
    '/api/projects/:projectId/files/upload',
    raw({ type: '*/*', limit: uploadBodyLimit }),
    async (req: Request<{ projectId: string }, unknown, Buffer>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      const name = typeof req.query.name === 'string' ? req.query.name.trim() : '';
      const kind = typeof req.query.kind === 'string' ? req.query.kind.trim() : '';
      const mimeTypeFromQuery = typeof req.query.mimeType === 'string' ? req.query.mimeType.trim() : '';
      const mimeType = mimeTypeFromQuery || req.header('content-type')?.trim() || 'application/octet-stream';
      const buffer = Buffer.isBuffer(req.body) ? req.body : Buffer.alloc(0);

      if (!name || !kind || !mimeType || buffer.byteLength === 0) {
        res.status(400).json({ message: 'name, kind, mimeType and binary body are required' });
        return;
      }

      if (kind !== 'novel_source' && kind !== 'asset_attachment') {
        res.status(400).json({ message: 'kind must be novel_source or asset_attachment' });
        return;
      }

      const file = storeProjectFileBuffer(record.project.id, {
        name,
        kind,
        mimeType,
        buffer
      });

      record.storedFiles = record.storedFiles.concat(file);
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: 'source_file_uploaded',
        summary: `上传源文件「${file.name}」`,
        detail: `已存储 ${file.kind} 文件，大小 ${file.byteSize} 字节。`,
        metadata: {
          byteSize: file.byteSize,
          kind: file.kind
        }
      });
      await projectRepository.save(record);

      res.status(201).json(file);
    }
  );

  router.post(
    '/api/projects/:projectId/files',
    async (req: Request<{ projectId: string }, unknown, CreateStoredFileInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      if (!req.body?.name?.trim() || !req.body?.kind || !req.body?.mimeType?.trim() || !req.body?.contentBase64?.trim()) {
        res.status(400).json({ message: 'name, kind, mimeType and contentBase64 are required' });
        return;
      }

      const file = storeProjectFile(record.project.id, req.body);
      record.storedFiles = record.storedFiles.concat(file);
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: 'source_file_uploaded',
        summary: `上传源文件「${file.name}」`,
        detail: `已存储 ${file.kind} 文件，大小 ${file.byteSize} 字节。`,
        metadata: {
          byteSize: file.byteSize,
          kind: file.kind
        }
      });
      await projectRepository.save(record);

      res.status(201).json(file);
    }
  );

  router.post(
    '/api/projects/:projectId/novel/upload-sessions',
    async (req: Request<{ projectId: string }, unknown, CreateUploadSessionInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      if (!req.body?.title?.trim() || !req.body?.totalChunks || req.body.totalChunks < 1) {
        res.status(400).json({ message: 'title and totalChunks are required' });
        return;
      }

      const uploadSession = {
        id: createId('upload'),
        projectId: record.project.id,
        title: req.body.title.trim(),
        author: req.body.author?.trim(),
        totalChunks: req.body.totalChunks,
        receivedChunks: 0,
        totalCharacters: 0,
        status: 'receiving' as const,
        chunks: Array.from({ length: req.body.totalChunks }, () => ''),
        createdAt: now(),
        updatedAt: now()
      };

      record.uploadSessions = record.uploadSessions
        .filter((session) => session.status !== 'receiving')
        .concat(uploadSession);
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: 'upload_session_created',
        summary: `创建长文本导入会话`,
        detail: `已为《${uploadSession.title}》创建分片导入会话，共 ${uploadSession.totalChunks} 片。`,
        metadata: {
          totalChunks: uploadSession.totalChunks
        }
      });
      await projectRepository.save(record);

      res.status(201).json(uploadSession);
    }
  );

  router.post(
    '/api/upload-sessions/:uploadSessionId/chunks',
    async (req: Request<{ uploadSessionId: string }, unknown, UploadChunkInput>, res) => {
      const snapshots = await projectRepository.list();
      const projectRecords = await Promise.all(snapshots.map((snapshot) => projectRepository.get(snapshot.project.id)));
      const record = projectRecords.find((item) => item?.uploadSessions.some((session) => session.id === req.params.uploadSessionId));

      if (!record) {
        res.status(404).json({ message: 'Upload session not found' });
        return;
      }

      const session = record.uploadSessions.find((item) => item.id === req.params.uploadSessionId);
      if (!session) {
        res.status(404).json({ message: 'Upload session not found' });
        return;
      }

      if (session.status !== 'receiving') {
        res.status(400).json({ message: 'Upload session is not receiving chunks' });
        return;
      }

      if (req.body?.index === undefined || req.body.index < 0 || req.body.index >= session.totalChunks || !req.body.content?.trim()) {
        res.status(400).json({ message: 'valid index and content are required' });
        return;
      }

      const wasFilled = Boolean(session.chunks[req.body.index]);
      session.chunks[req.body.index] = req.body.content;
      session.receivedChunks = session.chunks.filter(Boolean).length;
      session.totalCharacters = session.chunks.reduce((total, chunk) => total + chunk.length, 0);
      session.updatedAt = now();

      if (!wasFilled && session.receivedChunks === session.totalChunks) {
        session.status = 'assembled';
      }

      record.project.updatedAt = now();
      await projectRepository.save(record);

      res.status(200).json(session);
    }
  );

  router.post('/api/upload-sessions/:uploadSessionId/finalize', async (req, res) => {
    const snapshots = await projectRepository.list();
    const projectRecords = await Promise.all(snapshots.map((snapshot) => projectRepository.get(snapshot.project.id)));
    const record = projectRecords.find((item) => item?.uploadSessions.some((session) => session.id === req.params.uploadSessionId));

    if (!record) {
      res.status(404).json({ message: 'Upload session not found' });
      return;
    }

    const session = record.uploadSessions.find((item) => item.id === req.params.uploadSessionId);
    if (!session) {
      res.status(404).json({ message: 'Upload session not found' });
      return;
    }

    if (session.receivedChunks !== session.totalChunks) {
      res.status(400).json({ message: 'all chunks must be uploaded before finalize' });
      return;
    }

    const text = session.chunks.join('\n\n');
    const result = importNovel(record.project.id, {
      title: session.title,
      author: session.author,
      text
    });

    record.novel = result.novel;
    record.characters = result.characters;
    clearGeneratedOutputs(record, { keepAssets: true, keepUploadSessions: true });
    session.status = 'imported';
    session.updatedAt = now();
    record.project.stage = 'novel_imported';
    record.project.updatedAt = now();
    appendVersion(record, {
      stage: record.project.stage,
      action: 'upload_session_completed',
      summary: `分片导入完成《${session.title}》`,
      detail: `共接收 ${session.totalChunks} 片，累计 ${session.totalCharacters} 字符，并已完成小说导入。`,
      metadata: {
        totalChunks: session.totalChunks,
        totalCharacters: session.totalCharacters
      }
    });
    appendVersion(record, {
      stage: record.project.stage,
      action: 'novel_imported',
      summary: `导入小说《${result.novel.title}》`,
      detail: `完成原著导入，共切分 ${result.novel.chapterCount} 章，抽取 ${result.characters.length} 个核心角色。`,
      metadata: {
        chapterCount: result.novel.chapterCount,
        characterCount: result.characters.length,
        wordCount: result.novel.wordCount
      }
    });
    applyBaselineEpisodePackage(record);
    await projectRepository.save(record);

    res.status(201).json(record);
  });

  router.post(
    '/api/projects/:projectId/assets',
    async (req: Request<{ projectId: string }, unknown, CreateAssetItemInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      if (!req.body?.name?.trim() || !req.body?.description?.trim() || !req.body?.type) {
        res.status(400).json({ message: 'name, type and description are required' });
        return;
      }

      if (req.body.sourceFileId && !record.storedFiles.some((file) => file.id === req.body.sourceFileId)) {
        res.status(400).json({ message: 'sourceFileId not found' });
        return;
      }

      const asset = {
        id: createId('asset'),
        projectId: record.project.id,
        name: req.body.name.trim(),
        type: req.body.type,
        status: 'ready' as const,
        description: req.body.description.trim(),
        sourceUrl: req.body.sourceUrl?.trim() || undefined,
        sourceFileId: req.body.sourceFileId?.trim() || undefined,
        tags: (req.body.tags || []).map((tag) => tag.trim()).filter(Boolean),
        promptHint: req.body.promptHint?.trim() || undefined,
        createdAt: now(),
        updatedAt: now()
      };

      record.assets = record.assets.concat(asset);
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: 'asset_registered',
        summary: `登记素材资产「${asset.name}」`,
        detail: `新增 ${asset.type} 资产，可供后续分镜、预演和出片任务复用。`,
        metadata: {
          assetType: asset.type,
          tagCount: asset.tags.length
        }
      });
      await projectRepository.save(record);

      res.status(201).json(asset);
    }
  );

  router.post(
    '/api/projects/:projectId/import-jobs',
    async (req: Request<{ projectId: string }, unknown, CreateImportJobInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      if (!req.body?.fileId?.trim() || !req.body?.title?.trim()) {
        res.status(400).json({ message: 'fileId and title are required' });
        return;
      }

      const file = record.storedFiles.find((item) => item.id === req.body.fileId);
      if (!file) {
        res.status(400).json({ message: 'source file not found' });
        return;
      }

      const initialTitle =
        isWeakTitle(req.body.title) && !isSuspiciousStoredFilename(file.name) ? deriveTitleFromStoredFilename(file.name) || req.body.title : req.body.title;
      const job = createImportJob(record.project.id, { ...req.body, title: initialTitle });
      record.importJobs = record.importJobs.concat(job);
      appendVersion(record, {
        stage: record.project.stage,
        action: 'import_job_created',
        summary: `创建导入任务「${job.title}」`,
        detail: `已从文件「${file.name}」创建导入任务。`,
        metadata: {
          fileId: file.id
        }
      });

      try {
        markImportJobRunning(job);
        const text = readStoredTextFile(file);
        const inferredTitle = inferNovelTitleFromText(text, file.name);
        const resolvedTitle = isWeakTitle(job.title) && inferredTitle ? inferredTitle : job.title;
        job.title = resolvedTitle;
        if (inferredTitle && isSuspiciousStoredFilename(file.name)) {
          file.name = recoverStoredFilename(file.name, inferredTitle);
        }
        const result = importNovel(record.project.id, {
          title: resolvedTitle,
          author: job.author,
          text
        });

        record.novel = result.novel;
        record.characters = result.characters;
        clearImportState(record, { keepAssets: true, keepStoredFiles: true });
        record.importJobs = record.importJobs.filter((item) => item.id !== job.id).concat(job);
        markImportJobCompleted(job, result.novel);
        record.project.stage = 'novel_imported';
        record.project.updatedAt = now();
        appendVersion(record, {
          stage: record.project.stage,
          action: 'import_job_completed',
          summary: `导入任务完成「${job.title}」`,
          detail: `已完成源文件导入，累计 ${result.novel.wordCount} 字，并切分 ${result.novel.chapterCount} 章。`,
          metadata: {
            wordCount: result.novel.wordCount,
            chapterCount: result.novel.chapterCount
          }
        });
        appendVersion(record, {
          stage: record.project.stage,
          action: 'novel_imported',
          summary: `导入小说《${result.novel.title}》`,
          detail: `完成原著导入，共切分 ${result.novel.chapterCount} 章，抽取 ${result.characters.length} 个核心角色。`,
          metadata: {
            chapterCount: result.novel.chapterCount,
            characterCount: result.characters.length,
            wordCount: result.novel.wordCount
          }
        });
        applyBaselineEpisodePackage(record);
      } catch (error) {
        markImportJobFailed(job, error instanceof Error ? error.message : 'unknown error');
      }

      await projectRepository.save(record);
      res.status(201).json(job);
    }
  );

  router.post('/api/projects/:projectId/novel/import', async (req: Request<{ projectId: string }, unknown, ImportNovelInput>, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    if (!req.body?.title?.trim() || !req.body?.text?.trim()) {
      res.status(400).json({ message: 'title and text are required' });
      return;
    }

    const result = importNovel(record.project.id, req.body);
    record.novel = result.novel;
    record.characters = result.characters;
    clearImportState(record, { keepAssets: true, keepStoredFiles: true });
    record.project.stage = 'novel_imported';
    record.project.updatedAt = now();
    appendVersion(record, {
      stage: record.project.stage,
      action: 'novel_imported',
      summary: `导入小说《${result.novel.title}》`,
      detail: `完成原著导入，共切分 ${result.novel.chapterCount} 章，抽取 ${result.characters.length} 个核心角色。`,
      metadata: {
        chapterCount: result.novel.chapterCount,
        characterCount: result.characters.length,
        wordCount: result.novel.wordCount
      }
    });
    applyBaselineEpisodePackage(record);
    await projectRepository.save(record);

    res.status(201).json(record);
  });

  router.post(
    '/api/projects/:projectId/adaptation/episode-outline',
    async (req: Request<{ projectId: string }, unknown, GenerateEpisodeOutlineInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      if (!record.novel) {
        res.status(400).json({ message: 'import novel first' });
        return;
      }

      const input = req.body;
      if (!input?.episodeNo) {
        res.status(400).json({ message: 'episodeNo is required' });
        return;
      }

      const outline = generateEpisodeOutline(record.project.id, record.novel.title, record.novel.chapters, input);
      clearEpisodeOutputs(record, outline.episodeNo);
      record.episodeOutlines = record.episodeOutlines.concat(outline);
      record.project.stage = 'episode_outlined';
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: 'episode_outline_generated',
        summary: `生成第 ${outline.episodeNo} 集集纲`,
        detail: `完成第 ${outline.episodeNo} 集集纲，模式为 ${outline.adaptationMode}，预估时长 ${outline.estimatedMinutes} 分钟。`,
        metadata: {
          episodeNo: outline.episodeNo,
          estimatedMinutes: outline.estimatedMinutes
        }
      });
      await projectRepository.save(record);

      res.status(201).json(outline);
    }
  );

  router.post('/api/episode-outlines/:episodeOutlineId/scenes/generate', async (req, res) => {
    const snapshots = await projectRepository.list();
    const projectRecords = await Promise.all(snapshots.map((snapshot) => projectRepository.get(snapshot.project.id)));
    const record = projectRecords
      .find((item) => item?.episodeOutlines.some((outline) => outline.id === req.params.episodeOutlineId));

    if (!record) {
      res.status(404).json({ message: 'Episode outline not found' });
      return;
    }

    const outline = record.episodeOutlines.find((item) => item.id === req.params.episodeOutlineId);
    if (!outline) {
      res.status(404).json({ message: 'Episode outline not found' });
      return;
    }

    const scenes = generateScenes(record.project.id, outline, record.characters, record.novel?.chapters || []);
    record.scenes = record.scenes.filter((scene) => scene.episodeOutlineId !== outline.id).concat(scenes);
    record.previewJobs = record.previewJobs.filter((job) => job.episodeNo !== outline.episodeNo);
    record.renderJobs = record.renderJobs.filter((job) => job.episodeNo !== outline.episodeNo);
    record.project.stage = 'scene_scripted';
    record.project.updatedAt = now();
    appendVersion(record, {
      stage: record.project.stage,
      action: 'scene_scripts_generated',
      summary: `生成第 ${outline.episodeNo} 集分场`,
      detail: `围绕第 ${outline.episodeNo} 集集纲输出 ${scenes.length} 个可制作分场。`,
      metadata: {
        episodeNo: outline.episodeNo,
        sceneCount: scenes.length
      }
    });
    await projectRepository.save(record);

    res.status(201).json(scenes);
  });

  router.post('/api/scenes/:sceneId/shots/generate', async (req, res) => {
    const snapshots = await projectRepository.list();
    const projectRecords = await Promise.all(snapshots.map((snapshot) => projectRepository.get(snapshot.project.id)));
    const record = projectRecords
      .find((item) => item?.scenes.some((scene) => scene.id === req.params.sceneId));

    if (!record) {
      res.status(404).json({ message: 'Scene not found' });
      return;
    }

    const scene = record.scenes.find((item) => item.id === req.params.sceneId);
    if (!scene) {
      res.status(404).json({ message: 'Scene not found' });
      return;
    }
    const outline = record.episodeOutlines.find((item) => item.id === scene.episodeOutlineId);

    const shots = generateShots(record.project.id, scene);
    record.shots = record.shots.filter((shot) => shot.sceneId !== scene.id).concat(shots);
    if (outline) {
      record.previewJobs = record.previewJobs.filter((job) => job.episodeNo !== outline.episodeNo);
      record.renderJobs = record.renderJobs.filter((job) => job.episodeNo !== outline.episodeNo);
    }
    record.project.stage = 'shot_scripted';
    record.project.updatedAt = now();
    appendVersion(record, {
      stage: record.project.stage,
      action: 'shot_scripts_generated',
      summary: `生成场次 ${scene.sceneNo} 分镜`,
      detail: `为场次 ${scene.sceneNo}「${scene.title}」生成 ${shots.length} 个基础镜头脚本。`,
      metadata: {
        sceneNo: scene.sceneNo,
        shotCount: shots.length
      }
    });
    await projectRepository.save(record);

    res.status(201).json(shots);
  });

  router.post('/api/projects/:projectId/review/consistency', async (req, res) => {
    const record = await getProjectOr404(req.params.projectId, res);
    if (!record) {
      return;
    }

    record.issues = reviewConsistency(record.project.id, record.scenes, record.shots, {
      characters: record.characters,
      outline: record.episodeOutlines.at(-1)
    });
    record.project.stage = 'reviewed';
    record.project.updatedAt = now();
    appendVersion(record, {
      stage: record.project.stage,
      action: 'consistency_reviewed',
      summary: '完成一致性审查',
      detail: `审查完成，当前共识别 ${record.issues.length} 个需要关注的问题。`,
      metadata: {
        issueCount: record.issues.length
      }
    });
    await projectRepository.save(record);

    res.status(201).json(record.issues);
  });

  router.post(
    '/api/projects/:projectId/pipeline/episode-package',
    async (req: Request<{ projectId: string }, unknown, GenerateEpisodeOutlineInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      if (!record.novel) {
        res.status(400).json({ message: 'import novel first' });
        return;
      }

      const input = req.body;
      if (!input?.episodeNo) {
        res.status(400).json({ message: 'episodeNo is required' });
        return;
      }

      const episodePackage = buildEpisodePackage(
        record.project.id,
        record.novel.title,
        record.novel.chapters,
        record.characters,
        input
      );
      clearEpisodeOutputs(record, episodePackage.outline.episodeNo);
      record.episodeOutlines = record.episodeOutlines.concat(episodePackage.outline);
      record.scenes = record.scenes.concat(episodePackage.scenes);
      record.shots = record.shots.concat(episodePackage.shots);
      record.issues = episodePackage.issues;
      record.project.stage = 'reviewed';
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: 'episode_package_generated',
        summary: `生成第 ${episodePackage.outline.episodeNo} 集整包`,
        detail: `输出第 ${episodePackage.outline.episodeNo} 集整包：${episodePackage.scenes.length} 个分场、${episodePackage.shots.length} 个分镜、${episodePackage.issues.length} 条审查结果。`,
        metadata: {
          episodeNo: episodePackage.outline.episodeNo,
          sceneCount: episodePackage.scenes.length,
          shotCount: episodePackage.shots.length,
          issueCount: episodePackage.issues.length
        }
      });
      await projectRepository.save(record);

      res.status(201).json(episodePackage);
    }
  );

  router.post(
    '/api/projects/:projectId/preview-jobs',
    async (req: Request<{ projectId: string }, unknown, CreatePreviewVideoJobInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      const episodeNo = req.body?.episodeNo;
      if (!episodeNo) {
        res.status(400).json({ message: 'episodeNo is required' });
        return;
      }

      const outline = record.episodeOutlines.find((item) => item.episodeNo === episodeNo);
      if (!outline) {
        res.status(400).json({ message: 'generate episode outline or package first' });
        return;
      }

      const scenes = record.scenes.filter((scene) => scene.episodeOutlineId === outline.id);
      if (scenes.length === 0) {
        res.status(400).json({ message: 'generate scenes first' });
        return;
      }

      const sceneIds = new Set(scenes.map((scene) => scene.id));
      const shots = record.shots.filter((shot) => sceneIds.has(shot.sceneId));
      if (shots.length === 0) {
        res.status(400).json({ message: 'generate shots first' });
        return;
      }

      const previewJob = preparePreviewVideoJob({
        projectId: record.project.id,
        outline,
        scenes,
        shots,
        issues: record.issues,
        request: req.body
      });

      record.previewJobs = record.previewJobs
        .filter((job) => !(job.episodeNo === previewJob.episodeNo && job.provider === previewJob.provider))
        .concat(previewJob);
      record.renderJobs = record.renderJobs.filter((job) => job.episodeNo !== previewJob.episodeNo);
      record.project.stage = 'preview_prepared';
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: 'preview_job_prepared',
        summary: `预演包已就绪（第 ${previewJob.episodeNo} 集）`,
        detail: `已为第 ${previewJob.episodeNo} 集生成 ${previewJob.provider} 预演交付包，含 ${previewJob.sceneCount} 场与 ${previewJob.shotCount} 镜头提示。`,
        metadata: {
          episodeNo: previewJob.episodeNo,
          sceneCount: previewJob.sceneCount,
          shotCount: previewJob.shotCount
        }
      });
      await projectRepository.save(record);

      res.status(201).json(previewJob);
    }
  );

  router.post(
    '/api/projects/:projectId/render-jobs',
    async (req: Request<{ projectId: string }, unknown, CreateRenderJobInput>, res) => {
      const record = await getProjectOr404(req.params.projectId, res);
      if (!record) {
        return;
      }

      const episodeNo = req.body?.episodeNo;
      if (!episodeNo) {
        res.status(400).json({ message: 'episodeNo is required' });
        return;
      }

      const previewJob = record.previewJobs
        .filter((job) => job.episodeNo === episodeNo)
        .sort((left, right) => right.createdAt.localeCompare(left.createdAt))[0];
      if (!previewJob) {
        res.status(400).json({ message: 'prepare preview job first' });
        return;
      }

      const renderJob = dispatchRenderJob({
        projectId: record.project.id,
        previewJob,
        request: req.body
      });

      record.renderJobs = record.renderJobs
        .filter((job) => !(job.episodeNo === renderJob.episodeNo && job.provider === renderJob.provider))
        .concat(renderJob);
      record.project.stage = renderJob.status === 'completed' ? 'render_completed' : 'render_submitted';
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: renderJob.status === 'completed' ? 'render_job_completed' : 'render_job_dispatched',
        summary: `第 ${renderJob.episodeNo} 集出片任务已提交`,
        detail: `已提交 ${renderJob.provider} 出片任务，质量档位为 ${renderJob.qualityPreset}，当前状态 ${renderJob.status}。`,
        metadata: {
          episodeNo: renderJob.episodeNo,
          provider: renderJob.provider,
          qualityPreset: renderJob.qualityPreset
        }
      });
      await projectRepository.save(record);

      res.status(201).json(renderJob);
    }
  );

  router.post(
    '/api/render-jobs/:renderJobId/status',
    async (req: Request<{ renderJobId: string }, unknown, UpdateRenderJobStatusInput>, res) => {
      const snapshots = await projectRepository.list();
      const projectRecords = await Promise.all(snapshots.map((snapshot) => projectRepository.get(snapshot.project.id)));
      const record = projectRecords.find((item) => item?.renderJobs.some((job) => job.id === req.params.renderJobId));

      if (!record) {
        res.status(404).json({ message: 'Render job not found' });
        return;
      }

      const renderJob = record.renderJobs.find((job) => job.id === req.params.renderJobId);
      if (!renderJob) {
        res.status(404).json({ message: 'Render job not found' });
        return;
      }

      if (!req.body?.status) {
        res.status(400).json({ message: 'status is required' });
        return;
      }

      renderJob.status = req.body.status;
      renderJob.outputSummary = req.body.outputSummary?.trim() || renderJob.outputSummary;
      renderJob.externalJobId = req.body.externalJobId?.trim() || renderJob.externalJobId;
      renderJob.warnings = req.body.warnings || renderJob.warnings;
      renderJob.artifacts = req.body.artifacts || renderJob.artifacts;
      renderJob.updatedAt = now();

      record.project.stage = renderJob.status === 'completed' ? 'render_completed' : 'render_submitted';
      record.project.updatedAt = now();
      appendVersion(record, {
        stage: record.project.stage,
        action: renderJob.status === 'completed' ? 'render_job_completed' : 'render_job_dispatched',
        summary: `第 ${renderJob.episodeNo} 集出片状态更新`,
        detail: `出片任务 ${renderJob.provider} 状态已更新为 ${renderJob.status}。`,
        metadata: {
          episodeNo: renderJob.episodeNo,
          provider: renderJob.provider,
          status: renderJob.status
        }
      });
      await projectRepository.save(record);

      res.status(200).json(renderJob);
    }
  );

  return router;
}
