import { Injectable, Logger } from '@nestjs/common';
import { EngineAdapter, EngineInvokeInput, EngineInvokeResult } from '@scu/shared-types';
import Replicate from 'replicate';
import axios from 'axios';
import * as fs from 'fs';
import { createHash } from 'crypto';
import { pipeline } from 'stream/promises';
import * as path from 'path';

/**
 * Shot Render Replicate Adapter (REAL - Production)
 *
 * Phase 0-R: Production Video Seal
 * - Uses Replicate SDXL for real image generation
 * - Downloads to apps/workers/.runtime/assets
 * - Calculates real SHA256
 * - No mock:// or mocked:true
 */
@Injectable()
export class ShotRenderReplicateAdapter implements EngineAdapter {
  public readonly name = 'shot_render_replicate';
  private readonly logger = new Logger(ShotRenderReplicateAdapter.name);
  private replicate: Replicate;
  private readonly ASSETS_DIR = path.join(process.cwd(), 'apps/workers/.runtime/assets');

  constructor() {
    // Ensure assets directory exists
    if (!fs.existsSync(this.ASSETS_DIR)) {
      fs.mkdirSync(this.ASSETS_DIR, { recursive: true });
    }
  }

  private getReplicate(): Replicate {
    if (this.replicate) return this.replicate;

    const token = process.env.REPLICATE_API_TOKEN;
    if (!token) {
      throw new Error('REPLICATE_API_TOKEN not configured in environment');
    }
    this.replicate = new Replicate({ auth: token });
    return this.replicate;
  }

  supports(engineKey: string): boolean {
    return (
      engineKey === 'shot_render' ||
      engineKey === 'default_shot_render' ||
      engineKey === 'real_shot_render'
    );
  }

  async invoke(input: EngineInvokeInput): Promise<EngineInvokeResult> {
    const prompt = input.payload.enrichedPrompt || input.payload.prompt;
    const seed = input.payload.seed || Math.floor(Math.random() * 1000000);
    const traceId = input.context?.traceId || input.context?.jobId || `trace_${Date.now()}`;

    if (!prompt) {
      throw new Error('Missing enrichedPrompt or prompt in payload');
    }

    const startTime = Date.now();

    try {
      this.logger.log(
        `[ShotRenderReplicate] Generating image for prompt: ${prompt.substring(0, 50)}...`
      );

      // 1. Call Replicate SDXL (Using predictions.create for ID)
      const model =
        'stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b';
      const [modelName, modelVersion] = model.split(':');

      const prediction = await this.getReplicate().predictions.create({
        version: modelVersion,
        input: {
          prompt: prompt,
          seed: seed,
          width: 1024,
          height: 1024,
          num_outputs: 1,
          scheduler: 'K_EULER',
          num_inference_steps: 20,
        },
      });

      this.logger.log(`[ShotRenderReplicate] Prediction created: ${prediction.id}`);

      const predictionResult = await this.getReplicate().wait(prediction);

      if (predictionResult.status === 'failed') {
        throw new Error(`Replicate prediction failed: ${predictionResult.error}`);
      }

      const output = predictionResult.output as string[];

      if (!output || output.length === 0) {
        throw new Error('Replicate returned empty output');
      }

      const imageUrl = output[0];
      this.logger.log(`[ShotRenderReplicate] Image generated: ${imageUrl}`);

      // 2. Download image to .runtime/assets (not /tmp)
      const filename = `shot_${traceId}_${seed}.png`;
      const localPath = path.join(this.ASSETS_DIR, filename);
      await this.downloadImage(imageUrl, localPath);

      // 3. Calculate real SHA256
      const sha256 = await this.calculateSHA256(localPath);

      // 4. Get file size
      const stats = fs.statSync(localPath);
      const fileSize = stats.size;

      const latency = Date.now() - startTime;

      this.logger.log(
        `[ShotRenderReplicate] Success - File: ${localPath}, Size: ${fileSize} bytes, SHA256: ${sha256.substring(0, 16)}...`
      );

      return {
        status: 'SUCCESS' as any,
        output: {
          asset: {
            uri: localPath, // ✅ Real local path
            sha256: sha256, // ✅ Real SHA256
          },
          render_meta: {
            width: 1024,
            height: 1024,
            mocked: false, // ✅ Not mocked
            engine: 'replicate_sdxl',
            seed: seed,
            prompt: prompt,
            replicateUrl: imageUrl,
            fileSize: fileSize,
            engine_run_id: prediction.id, // Audit Key
            engine_provider: 'replicate',
            engine_model: model,
          },
          audit_trail: {
            message: 'Generated by Replicate SDXL',
            engine: this.name,
            timestamp: new Date().toISOString(),
            prompt_hash: createHash('sha256').update(prompt).digest('hex'),
            engineKey: 'shot_render',
            traceId: traceId,
            engineRunId: prediction.id,
          },
        },
        metrics: {
          latencyMs: latency,
          gpuSeconds: 2.5, // SDXL estimate
        },
      };
    } catch (error: any) {
      this.logger.error(`[ShotRenderReplicate] Failed: ${error.message}`);
      return {
        status: 'FAILED' as any,
        error: {
          code: 'SHOT_RENDER_FAILED',
          message: error.message,
        },
      };
    }
  }

  private async downloadImage(url: string, localPath: string): Promise<void> {
    const response = await axios.get(url, { responseType: 'stream' });
    await pipeline(response.data, fs.createWriteStream(localPath));
  }

  private async calculateSHA256(filePath: string): Promise<string> {
    const hash = createHash('sha256');
    const stream = fs.createReadStream(filePath);

    return new Promise((resolve, reject) => {
      stream.on('data', (chunk) => hash.update(chunk as any));
      stream.on('end', () => resolve(hash.digest('hex')));
      stream.on('error', reject);
    });
  }
}
