import { Injectable, Logger } from '@nestjs/common';
import { EngineAdapter, EngineInvokeInput, EngineInvokeResult } from '@scu/shared-types';
import * as fs from 'fs';
import { createHash } from 'crypto';
import * as path from 'path';
import { comfyuiProvider } from '../../../../../packages/engines/shot_render/providers/comfyui.provider';

/**
 * Shot Render ComfyUI Adapter (REAL - Local)
 *
 * Stage 2: Local ComfyUI Provider
 * - Calls local ComfyUI for real image generation
 * - Downloads to apps/workers/.runtime/assets
 * - Calculates real SHA256
 */
@Injectable()
export class ShotRenderComfyuiAdapter implements EngineAdapter {
  public readonly name = 'shot_render_comfyui';
  private readonly logger = new Logger(ShotRenderComfyuiAdapter.name);
  private readonly ASSETS_DIR = path.join(process.cwd(), 'apps/workers/.runtime/assets');

  constructor() {
    // Ensure assets directory exists
    if (!fs.existsSync(this.ASSETS_DIR)) {
      fs.mkdirSync(this.ASSETS_DIR, { recursive: true });
    }
  }

  supports(engineKey: string): boolean {
    return (
      engineKey === 'shot_render_comfyui'
    );
  }

  async invoke(input: EngineInvokeInput): Promise<EngineInvokeResult> {
    const prompt = input.payload.enrichedPrompt || input.payload.prompt;
    const seed = input.payload.seed || Math.floor(Math.random() * 1000000);
    // Use traceId or jobId for unique filename
    const traceId = input.context?.traceId || input.context?.jobId || `trace_${Date.now()}`;

    if (!prompt) {
      throw new Error('Missing enrichedPrompt or prompt in payload');
    }

    const startTime = Date.now();

    try {
      this.logger.log(
        `[ShotRenderComfyui] Generating image for prompt: ${prompt.substring(0, 50)}...`
      );

      // 1. Call ComfyUI Provider with dynamic Graph Injection
      const result = await comfyuiProvider.render(prompt, {
        width: 1024,
        height: 1024,
        seed,
        checkpoint: input.payload.checkpoint || 'sdxl_guoman_v4.safetensors',
        loras: input.payload.loras || [],
        negativePrompt: input.payload.negative_prompt,
      });

      // 2. Write to .runtime/assets
      const filename = `shot_${traceId}_${seed}.png`;
      const localPath = path.join(this.ASSETS_DIR, filename);
      fs.writeFileSync(localPath, result.bytes);

      // 3. Calculate real SHA256
      const sha256 = createHash('sha256').update(result.bytes).digest('hex');

      // 4. Get file size
      const fileSize = result.bytes.length;

      const latency = Date.now() - startTime;

      this.logger.log(
        `[ShotRenderComfyui] Success - File: ${localPath}, Size: ${fileSize} bytes, SHA256: ${sha256.substring(0, 16)}...`
      );

      return {
        status: 'SUCCESS' as any,
        output: {
          asset: {
            uri: localPath, // ✅ Real local path
            sha256: sha256, // ✅ Real SHA256
          },
          render_meta: {
            width: 1024,
            height: 1024,
            mocked: false, // ✅ Not mocked
            engine: 'comfyui_sdxl',
            seed: seed,
            prompt: prompt,
            fileSize: fileSize,
          },
          audit_trail: {
            message: 'Generated by ComfyUI SDXL',
            engine: this.name,
            timestamp: new Date().toISOString(),
            prompt_hash: createHash('sha256').update(prompt).digest('hex'),
            engineKey: 'shot_render',
            traceId: traceId,
          },
        },
        metrics: {
          latencyMs: latency,
          gpuSeconds: result.gpuSeconds,
        },
      };
    } catch (error: any) {
      this.logger.error(`[ShotRenderComfyui] Failed: ${error.message}`);
      return {
        status: 'FAILED' as any,
        error: {
          code: 'SHOT_RENDER_FAILED',
          message: error.message,
        },
      };
    }
  }
}
