import { Injectable, Logger } from '@nestjs/common';
import { EngineAdapter, EngineInvokeInput, EngineInvokeResult } from '@scu/shared-types';
import { localMpsProvider } from '@scu/engines-shot-render';
import { createHash } from 'crypto';

/**
 * Shot Render MPS Adapter (REAL - Local Metal)
 *
 * Provides high-fidelity local generation using Stable Diffusion on Apple Silicon.
 * Uses the localMpsProvider which spawns a python process for sd15_mps.py.
 */
@Injectable()
export class ShotRenderMpsAdapter implements EngineAdapter {
  public readonly name = 'shot_render_mps';
  private readonly logger = new Logger(ShotRenderMpsAdapter.name);

  supports(engineKey: string): boolean {
    return (
      engineKey === 'shot_render' ||
      engineKey === 'default_shot_render' ||
      engineKey === 'real_shot_render' ||
      engineKey === 'shot_render_mps'
    );
  }

  async invoke(input: EngineInvokeInput): Promise<EngineInvokeResult> {
    const prompt = input.payload.prompt;
    const seed = input.payload.seed || Math.floor(Math.random() * 1000000);
    const shotId = (input.context?.shotId || input.payload?.shotId) as string;
    const traceId = (input.context?.traceId || input.payload?.traceId) as string;

    if (!prompt) {
      throw new Error('[ShotRenderMps] Missing prompt in payload');
    }
    if (!shotId || !traceId) {
      throw new Error(`[ShotRenderMps] Missing identity: shotId=${shotId}, traceId=${traceId}`);
    }

    const startTime = Date.now();

    try {
      this.logger.log(
        `[ShotRenderMps] Generating image for shotId=${shotId} via Local MPS (Stable Diffusion)...`
      );

      // Call the local MPS provider
      const result = await localMpsProvider.render(prompt, {
        width: 1024, // Optimized for MPS
        height: 1024,
        seed,
        shotId,
        traceId,
      });

      const latency = Date.now() - startTime;

      this.logger.log(
        `[ShotRenderMps] Success - File: ${result.asset_path}, Size: ${result.bytes.length} bytes, SHA256: ${result.sha256?.substring(0, 16)}...`
      );

      return {
        status: 'SUCCESS' as any,
        output: {
          asset: {
            uri: result.asset_path, // Normalized relative path from provider
            sha256: result.sha256,
          },
          render_meta: {
            width: result.width,
            height: result.height,
            mocked: false,
            engine: 'stable-diffusion-1.5-mps',
            seed: result.seed,
            prompt: prompt,
            model: result.model,
          },
          audit_trail: {
            message: 'Generated by local Stable Diffusion (MPS)',
            engine: this.name,
            timestamp: new Date().toISOString(),
            prompt_hash: createHash('sha256').update(prompt).digest('hex'),
            shotId,
            traceId,
          },
        },
        metrics: {
          latencyMs: latency,
          gpuSeconds: result.gpuSeconds,
        },
      };
    } catch (error: any) {
      this.logger.error(`[ShotRenderMps] Failed: ${error.message}`);
      return {
        status: 'FAILED' as any,
        error: {
          code: 'SHOT_RENDER_MPS_FAILED',
          message: error.message,
        },
      };
    }
  }
}
