import { Injectable, Logger } from '@nestjs/common';
import {
    EngineAdapter,
    EngineInvokeInput,
    EngineInvokeResult,
} from '@scu/shared-types';

@Injectable()
export class ShotRenderLocalAdapter implements EngineAdapter {
    public readonly name = 'shot_render_local';
    private readonly logger = new Logger(ShotRenderLocalAdapter.name);

    supports(engineKey: string): boolean {
        return (
            engineKey === 'shot_render' ||
            engineKey === 'default_shot_render' ||
            engineKey === 'real_shot_render' ||
            engineKey === 'http_shot_render'
        );
    }

    async invoke(input: EngineInvokeInput): Promise<EngineInvokeResult> {
        this.logger.log(
            `[ShotRenderLocal] Invoked for ${input.engineKey} (JobType=${input.jobType})`
        );

        // Return a Mock Asset valid structure for processShotRenderJob
        return {
            status: 'SUCCESS' as any,
            output: {
                asset: {
                    uri: 'mock://shot-render-result.png',
                    sha256: 'mock-sha256-hash'
                },
                render_meta: {
                    width: 1024,
                    height: 1024,
                    mocked: true
                },
                audit_trail: {
                    message: 'Generated by ShotRenderLocalAdapter (Mock)',
                    engine: this.name
                }
            },
        };
    }
}
