"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var ShotRenderMpsAdapter_1;
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShotRenderMpsAdapter = void 0;
const common_1 = require("@nestjs/common");
const engines_shot_render_1 = require("@scu/engines-shot-render");
const crypto_1 = require("crypto");
let ShotRenderMpsAdapter = ShotRenderMpsAdapter_1 = class ShotRenderMpsAdapter {
    name = 'shot_render_mps';
    logger = new common_1.Logger(ShotRenderMpsAdapter_1.name);
    supports(engineKey) {
        return (engineKey === 'shot_render' ||
            engineKey === 'default_shot_render' ||
            engineKey === 'real_shot_render' ||
            engineKey === 'shot_render_mps');
    }
    async invoke(input) {
        const prompt = input.payload.prompt;
        const seed = input.payload.seed || Math.floor(Math.random() * 1000000);
        const shotId = (input.context?.shotId || input.payload?.shotId);
        const traceId = (input.context?.traceId || input.payload?.traceId);
        if (!prompt) {
            throw new Error('[ShotRenderMps] Missing prompt in payload');
        }
        if (!shotId || !traceId) {
            throw new Error(`[ShotRenderMps] Missing identity: shotId=${shotId}, traceId=${traceId}`);
        }
        const startTime = Date.now();
        try {
            this.logger.log(`[ShotRenderMps] Generating image for shotId=${shotId} via Local MPS (Stable Diffusion)...`);
            const result = await engines_shot_render_1.localMpsProvider.render(prompt, {
                width: 1024,
                height: 1024,
                seed,
                shotId,
                traceId,
            });
            const latency = Date.now() - startTime;
            this.logger.log(`[ShotRenderMps] Success - File: ${result.asset_path}, Size: ${result.bytes.length} bytes, SHA256: ${result.sha256?.substring(0, 16)}...`);
            return {
                status: 'SUCCESS',
                output: {
                    asset: {
                        uri: result.asset_path,
                        sha256: result.sha256,
                    },
                    render_meta: {
                        width: result.width,
                        height: result.height,
                        mocked: false,
                        engine: 'stable-diffusion-1.5-mps',
                        seed: result.seed,
                        prompt: prompt,
                        model: result.model,
                    },
                    audit_trail: {
                        message: 'Generated by local Stable Diffusion (MPS)',
                        engine: this.name,
                        timestamp: new Date().toISOString(),
                        prompt_hash: (0, crypto_1.createHash)('sha256').update(prompt).digest('hex'),
                        shotId,
                        traceId,
                    },
                },
                metrics: {
                    latencyMs: latency,
                    gpuSeconds: result.gpuSeconds,
                },
            };
        }
        catch (error) {
            this.logger.error(`[ShotRenderMps] Failed: ${error.message}`);
            return {
                status: 'FAILED',
                error: {
                    code: 'SHOT_RENDER_MPS_FAILED',
                    message: error.message,
                },
            };
        }
    }
};
exports.ShotRenderMpsAdapter = ShotRenderMpsAdapter;
exports.ShotRenderMpsAdapter = ShotRenderMpsAdapter = ShotRenderMpsAdapter_1 = __decorate([
    (0, common_1.Injectable)()
], ShotRenderMpsAdapter);
//# sourceMappingURL=shot-render.mps.adapter.js.map