import { PrismaService } from '../prisma/prisma.service';
import { AuditLogService } from '../audit-log/audit-log.service';
import { Prisma, TaskType as TaskTypeEnum, TaskStatus as TaskStatusEnum } from 'database';
export declare class TaskService {
    private readonly prisma;
    private readonly auditLogService;
    constructor(prisma: PrismaService, auditLogService: AuditLogService);
    create(params: {
        organizationId: string;
        projectId: string;
        type: TaskTypeEnum;
        payload?: any;
        status?: TaskStatusEnum;
        attempts?: number;
        maxRetry?: number;
        retryCount?: number;
        error?: string;
        traceId?: string;
    }): Promise<{
        error: string | null;
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        type: import("database").$Enums.TaskType;
        status: import("database").$Enums.TaskStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        workerId: string | null;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        isVerification: boolean;
        dedupeKey: string | null;
        currentStep: string | null;
        output: Prisma.JsonValue | null;
    }>;
    findById(id: string): Promise<({
        jobs: {
            id: string;
            createdAt: Date;
            payload: Prisma.JsonValue | null;
            result: Prisma.JsonValue | null;
            type: import("database").$Enums.JobType;
            status: import("database").$Enums.JobStatus;
            updatedAt: Date;
            projectId: string;
            organizationId: string;
            traceId: string | null;
            episodeId: string | null;
            sceneId: string | null;
            shotId: string | null;
            taskId: string | null;
            workerId: string | null;
            priority: number;
            maxRetry: number;
            retryCount: number;
            attempts: number;
            leaseUntil: Date | null;
            lockedBy: string | null;
            engineConfig: Prisma.JsonValue | null;
            lastError: string | null;
            isVerification: boolean;
            dedupeKey: string | null;
            outputSha256: string | null;
            engineProvider: string | null;
            engineRunId: string | null;
            engineModel: string | null;
            securityProcessed: boolean;
            currentStep: string | null;
        }[];
    } & {
        error: string | null;
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        type: import("database").$Enums.TaskType;
        status: import("database").$Enums.TaskStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        workerId: string | null;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        isVerification: boolean;
        dedupeKey: string | null;
        currentStep: string | null;
        output: Prisma.JsonValue | null;
    }) | null>;
    updateStatus(id: string, status: TaskStatusEnum, payload?: any, errorMessage?: string, output?: any, workerId?: string | null): Promise<{
        error: string | null;
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        type: import("database").$Enums.TaskType;
        status: import("database").$Enums.TaskStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        workerId: string | null;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        isVerification: boolean;
        dedupeKey: string | null;
        currentStep: string | null;
        output: Prisma.JsonValue | null;
    }>;
}
