#!/usr/bin/env bash
# ==============================================================================
# [GATE] P0-R4: CE02 Mother -> video_merge (L2)
# Generated by Seal Factory v1.0
# ==============================================================================
set -euo pipefail
IFS=$'\n\t'
IFS=$'
	'

# ========== CONFIG ==========
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
EVID_ROOT="${ROOT_DIR}/docs/_evidence"
TS="$(date +"%Y%m%d_%H%M%S")"
EVID_DIR="${EVID_ROOT}/p0_r4_$(date +"%Y%m%d_%H%M%S")"
mkdir -p "${EVID_DIR}"

export GATE_MODE=1
export PRODUCTION_MODE=1
export VERIFICATION_COST_CAP_USD=1
export DATABASE_URL="${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/scu}"
export JWT_SECRET="${JWT_SECRET:-f0f4cb55a02a5bf2b2e9cbb273daf87991ad426e3ea68cf90cf394027c6ac23c9140290dce913869d9241aa675335d27}"

API_BASE="${API_BASE:-http://127.0.0.1:3000}"

# ========== HELPERS ==========
write_exit_code() { echo "$1" > "${EVID_DIR}/GATE_EXIT_CODE.txt"; }
sha256_sums() { (cd "${EVID_DIR}" && find . -maxdepth 1 -type f ! -name "SHA256SUMS.txt" -exec shasum -a 256 {} + > SHA256SUMS.txt); }
build_evidence_index() {
  export EVID_DIR="${EVID_DIR}"
  node - <<'JS'
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const evidDir = process.env.EVID_DIR;
const files = fs.readdirSync(evidDir).filter(n => fs.statSync(path.join(evidDir, n)).isFile() && n !== 'EVIDENCE_INDEX.json');
const out = { dir: evidDir, files: [] };
for (const name of files) {
  const p = path.join(evidDir, name);
  const b = fs.readFileSync(p);
  out.files.push({ name, bytes: b.length, sha256: crypto.createHash('sha256').update(b).digest('hex') });
}
fs.writeFileSync(path.join(evidDir, 'EVIDENCE_INDEX.json'), JSON.stringify(out, null, 2));
JS
}

# ========== MAIN ==========
echo "--- [GATE] P0-R4: video_merge (L2) START ---"

node tools/gate/gates/p0r0_seed_prisma.mjs > /dev/null
TOKEN=$(pnpm --prefix apps/api exec node -e "const jwt = require('jsonwebtoken'); console.log(jwt.sign({ sub: 'seal-factory', email: 'factory@test.com', orgId: 'org-factory', tier: 'PRO' }, process.env.JWT_SECRET, { expiresIn: '1h' }))")

TRACE_ID="gate-P0-R4-$(date +"%Y%m%d_%H%M%S")"
JOB_ID="job-P0-R4-$(date +"%Y%m%d_%H%M%S")"

cat > "${EVID_DIR}/REQ.json" <<JSON
{
  "engineKey": "video_merge",
  "payload": {"jobId": "${JOB_ID}", "framePaths": ["/tmp/f1.png"]},
  "metadata": {
    "isVerification": true,
    "traceId": "${TRACE_ID}",
    "jobId": "${JOB_ID}",
    "projectId": "proj-p0r0-gate"
  }
}
JSON

echo "Invoking Round 1..."
RESP="$(curl -sS -X POST "${API_BASE}/api/_internal/engine/invoke" \
  -H "content-type: application/json" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "x-gate-mode: 1" \
  -d @"${EVID_DIR}/REQ.json")"
echo "${RESP}" | jq . > "${EVID_DIR}/RUN.json"

if [ "$(echo "${RESP}" | jq -r '.data.success')" != "true" ]; then
  echo "❌ FAIL: Invocation failed"
  write_exit_code 3; exit 3
fi


echo "Invoking Round 2 (Idempotency Assert)..."
RESP2="$(curl -sS -X POST "${API_BASE}/api/_internal/engine/invoke" \
  -H "content-type: application/json" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "x-gate-mode: 1" \
  -d @"${EVID_DIR}/REQ.json")"
echo "${RESP2}" | jq . > "${EVID_DIR}/RUN_IDEMPOTENT.json"

# URI1=$(echo "${RESP}" | jq -r '.data.output.asset.uri')
URI2=$(echo "${RESP2}" | jq -r '.data.output.asset.uri')
if [ "${URI1}" != "${URI2}" ]; then echo "❌ FAIL: Idempotency broken"; write_exit_code 14; exit 14; fi


# SQL Evidence
psql -d "${DATABASE_URL}" -t -A -c "SELECT json_agg(t) FROM (
  SELECT id, action, \"resourceId\", details, payload, \"createdAt\"
  FROM audit_logs
  WHERE COALESCE(details->>'_traceId', payload->>'_traceId', payload->>'traceId') = '${TRACE_ID}'
) t" > "${EVID_DIR}/SQL_AUDIT.json"

psql -d "${DATABASE_URL}" -t -A -c "SELECT json_agg(t) FROM (
  SELECT id, \"costAmount\", currency, \"traceId\", \"jobId\", created_at
  FROM cost_ledgers
  WHERE \"traceId\" = '${TRACE_ID}'
) t" > "${EVID_DIR}/SQL_LEDGER.json"

echo '[]' > "${EVID_DIR}/SQL_JOB.json"
LEDGER_COUNT=$(psql -d "${DATABASE_URL}" -t -A -c "SELECT COUNT(*) FROM cost_ledgers WHERE \"traceId\"='${TRACE_ID}'")

if [ "${LEDGER_COUNT}" -ne 0 ]; then echo "❌ FAIL: Ledger contamination!"; write_exit_code 6; exit 6; fi

# Summary
cat > "${EVID_DIR}/SUMMARY.md" <<MD
# P0-R4 (L2) Summary
- Engine: video_merge
- TraceID: ${TRACE_ID}
- Ledger Count: ${LEDGER_COUNT} (Verified CLEAN)
- SQL_JOB.json: N/A (Direct invoke)
MD

write_exit_code 0
sha256_sums
build_evidence_index
echo "--- [GATE] P0-R4 PASS (L2) ---"
MD
