export declare const PRODUCTION_MODE: boolean;
export interface AppConfig {
    productionMode: boolean;
    nodeEnv: string;
    isDevelopment: boolean;
    isProduction: boolean;
    workerHeartbeatTimeoutMs: number;
    jobWatchdogEnabled: boolean;
    jobWatchdogTimeoutMs: number;
    databaseUrl: string;
    redisUrl: string;
    apiPort: number;
    apiHost: string;
    apiUrl: string;
    jwtSecret: string;
    jwtExpiresIn: string;
    jwtRefreshSecret: string;
    jwtRefreshExpiresIn: string;
    appName: string;
    appVersion: string;
    frontendUrl: string;
    bcryptSaltRounds: number;
    enableInternalJobWorker: boolean;
    jobWorkerInterval: number;
    jobWorkerBatchSize: number;
    workerApiKey?: string;
    workerApiSecret?: string;
    workerId: string;
    workerName: string;
    workerPollInterval: number;
    jobWorkerEnabled: boolean;
    engineDefault: string;
    engineRealHttpBaseUrl: string;
    HMAC_TIMESTAMP_WINDOW: number;
    HMAC_SIGNATURE_ALGORITHM: string;
    concurrencyLimiterEnabled: boolean;
    apiBackpressureEnabled: boolean;
    execTimeoutEnabled: boolean;
    retryPolicyEnabled: boolean;
    maxInFlightTotal: number;
    maxInFlightTenant: number;
    getEngineConcurrency: (engineKey: string) => number;
    apiQueuePendingLimit: number;
    apiQueueRunningLimit: number;
    apiRetryAfterSeconds: number;
    getEngineTimeoutSeconds: (engineKey: string) => number;
    retryMaxAttempts: number;
    retryBaseMs: number;
    retryMaxMs: number;
    retryJitter: boolean;
    jobMaxInFlight: number;
    jobWaveSize: number;
    jobBackpressureThreshold: number;
    jobLeaseTtlMs: number;
    workerOfflineGraceMs: number;
    storageRoot: string;
    ce23RealForceDisable: boolean;
    orchV2AudioEnabled: boolean;
    repoRoot: string;
}
export declare const env: AppConfig;
export declare function validateRequiredEnvs(): void;
export declare function pickHmacSecretSSOT(): string;
