import { PrismaService } from '../prisma/prisma.service';
import { EngineInvokerHubService } from '../engine-hub/engine-invoker-hub.service';
import { SemanticEnhancementEngineOutput, ShotPlanningEngineOutput, StructureQAEngineOutput } from '@scu/shared-types';
import { ProjectService } from '../project/project.service';
import { AuditLogService } from '../audit-log/audit-log.service';
export declare class Stage4Service {
    private readonly prisma;
    private readonly engineInvoker;
    private readonly projectService;
    private readonly auditLogService;
    private readonly logger;
    constructor(prisma: PrismaService, engineInvoker: EngineInvokerHubService, projectService: ProjectService, auditLogService: AuditLogService);
    ensureSceneInProject(projectId: string, sceneId: string): Promise<{
        episode: {
            id: string;
            name: string;
            status: string | null;
            projectId: string | null;
            summary: string | null;
            index: number;
            seasonId: string | null;
            buildId: string | null;
            sourceRefId: string | null;
            chapterId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        status: string | null;
        updatedAt: Date;
        projectId: string | null;
        summary: string | null;
        episodeId: string | null;
        title: string | null;
        characters: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        sceneIndex: number;
        buildId: string | null;
        sourceRefId: string | null;
        chapterId: string | null;
        visualDensityScore: import("../../../../packages/database/dist/generated/prisma/runtime/library").Decimal | null;
        visualDensityMeta: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        locationSlug: string | null;
        timeOfDay: string | null;
        environmentTags: string[];
        enrichedText: string | null;
        graphStateSnapshot: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        sceneDraftId: string | null;
        directingNotes: string | null;
        shotType: string | null;
        characterIds: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        entryStateJson: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        exitStateJson: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
    }>;
    ensureShotInProject(projectId: string, shotId: string): Promise<{
        scene: {
            episode: {
                id: string;
                name: string;
                status: string | null;
                projectId: string | null;
                summary: string | null;
                index: number;
                seasonId: string | null;
                buildId: string | null;
                sourceRefId: string | null;
                chapterId: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            status: string | null;
            updatedAt: Date;
            projectId: string | null;
            summary: string | null;
            episodeId: string | null;
            title: string | null;
            characters: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
            reviewStatus: import("database").$Enums.ShotReviewStatus;
            sceneIndex: number;
            buildId: string | null;
            sourceRefId: string | null;
            chapterId: string | null;
            visualDensityScore: import("../../../../packages/database/dist/generated/prisma/runtime/library").Decimal | null;
            visualDensityMeta: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
            locationSlug: string | null;
            timeOfDay: string | null;
            environmentTags: string[];
            enrichedText: string | null;
            graphStateSnapshot: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
            sceneDraftId: string | null;
            directingNotes: string | null;
            shotType: string | null;
            characterIds: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
            entryStateJson: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
            exitStateJson: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        };
    } & {
        params: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue;
        qualityScore: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue;
        id: string;
        type: string;
        description: string | null;
        organizationId: string | null;
        sceneId: string;
        index: number;
        title: string | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        buildId: string | null;
        sourceRefId: string | null;
        shotType: string | null;
        content: string | null;
        visualDescription: string | null;
        reviewedAt: Date | null;
        durationSeconds: number | null;
        enrichedPrompt: string | null;
        cameraMovement: string | null;
        cameraAngle: string | null;
        lightingPreset: string | null;
        renderStatus: import("database").$Enums.ShotRenderStatus;
        resultImageUrl: string | null;
        resultVideoUrl: string | null;
        visualPrompt: string | null;
        negativePrompt: string | null;
        actionDescription: string | null;
        dialogueContent: string | null;
        soundFx: string | null;
        assetBindings: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        controlnetSettings: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        durationSec: import("../../../../packages/database/dist/generated/prisma/runtime/library").Decimal | null;
        emotion: string | null;
        novelQuote: string | null;
        continuityJson: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
    }>;
    runSemanticEnhancement(projectId: string, sceneId: string, userId: string): Promise<SemanticEnhancementEngineOutput>;
    getSemanticEnhancement(sceneId: string): Promise<any>;
    runShotPlanning(projectId: string, shotId: string, userId: string): Promise<ShotPlanningEngineOutput>;
    getShotPlanning(shotId: string): Promise<any>;
    runStructureQA(projectId: string, userId: string): Promise<StructureQAEngineOutput>;
    getStructureQA(projectId: string): Promise<any>;
    recordAudit(action: string, resourceType: string, resourceId: string | null, userId: string, details?: any): Promise<void>;
}
