-- P16-2: Reliability Rollout & Rollback SQL
-- Target Table: "projects" (PostgreSQL table name for Prisma model Project)

-- ==========================================
-- ==========================================
-- ==========================================
-- [SOP] ALERTING & MONITORING (P16-2.3)
-- 1. 报警阈值 (Alert Thresholds):
--    - rework_rate_1h: >= max(5, baseline * 2) -> P0 Alert (Avoid 0-baseline trap)
--    - blocked_by_rate_limit_1h: Rising Trend (Series check) -> Warning
--    - ce23_guardrail_blocked_1h: >= 20/h -> Warning (Input Drift)
--    - ce23_real_marginal_fail_1h: >= 50/h -> Warning (Calibration needed)
--
-- [SOP] EMERGENCY RUNBOOK
-- 1. Real 爆炸: ⚠️ 必须先 CE23_REAL_FORCE_DISABLE=1 (Env Kill)，再执行 SQL Disable All (Section 3)。
-- 2. Shadow 异常: 直接 SQL Disable All (Section 3)。
-- 3. 恢复顺序 (Strict Order): Disable All (Section 3) -> Shadow Only (Section 2) -> 观察稳定 -> Whitelist Real (Section 5)。
-- ==========================================

-- ==========================================
-- Section 1: Rollback Real (Emergency Stop Real, Keep Shadow/Legacy)
-- Use this if Real Mode causes reworking storm or critical bugs.
-- ==========================================
-- UPDATE "projects"
-- SET "settingsJson" = jsonb_set(
--   coalesce("settingsJson", '{}'::jsonb),
--   '{ce23RealEnabled}',
--   'false'::jsonb,
--   true
-- )
-- WHERE id IN ('<PROJECT_ID_1>', '<PROJECT_ID_2>') -- TODO: Replace with target IDs
-- RETURNING id, "settingsJson";


-- ==========================================
-- Section 2: Enable Shadow Only (Widely Safe)
-- Use this to switch from Real back to Shadow, or enable Shadow on new projects.
-- ==========================================
-- UPDATE "projects"
-- SET "settingsJson" = jsonb_set(
--   jsonb_set(
--     coalesce("settingsJson", '{}'::jsonb),
--     '{ce23RealShadowEnabled}',
--     'true'::jsonb,
--     true
--   ),
--   '{ce23RealEnabled}',
--   'false'::jsonb,
--   true
-- )
-- WHERE id IN ('<PROJECT_ID_1>', '<PROJECT_ID_2>') -- TODO: Replace with target IDs
-- RETURNING id, "settingsJson";


-- ==========================================
-- Section 3: Disable All (Emergency Legacy Fallback)
-- Use this if Shadow also causes load issues or DB pressure.
-- ==========================================
-- UPDATE "projects"
-- SET "settingsJson" = jsonb_set(
--   jsonb_set(
--     coalesce("settingsJson", '{}'::jsonb),
--     '{ce23RealShadowEnabled}',
--     'false'::jsonb,
--     true
--   ),
--   '{ce23RealEnabled}',
--   'false'::jsonb,
--   true
-- )
-- WHERE id IN ('<PROJECT_ID_1>', '<PROJECT_ID_2>') -- TODO: Replace with target IDs
-- RETURNING id, "settingsJson";


-- ==========================================
-- Section 4: Shadow Whitelist Rollout (P16-2.1)
-- Enable Shadow Mode for a batch of projects (Safe for Broad Rollout).
-- ==========================================
-- UPDATE "projects"
-- SET "settingsJson" = jsonb_set(
--   jsonb_set(
--     coalesce("settingsJson", '{}'::jsonb),
--     '{ce23RealShadowEnabled}',
--     'true'::jsonb,
--     true
--   ),
--   '{ce23RealEnabled}',
--   'false'::jsonb,
--   true
-- )
-- WHERE "organizationId" IN ('<ORG_ID_1>', '<ORG_ID_2>') -- Batch by Org
--    OR "createdAt" > NOW() - INTERVAL '30 days';      -- Or Recent Projects
-- RETURNING id, "settingsJson";


-- ==========================================
-- Section 5: Enable Real Mode (Whitelist) - P16-2.2
-- ==========================================
-- UPDATE "projects"
-- SET "settingsJson" = jsonb_set(
--   jsonb_set(
--     jsonb_set(
--       jsonb_set(coalesce("settingsJson",'{}'::jsonb), '{ce23RealShadowEnabled}', 'true'::jsonb, true),
--       '{ce23RealEnabled}', 'true'::jsonb, true
--     ),
--     '{ce23RealGuardrailEnabled}', 'true'::jsonb, true
--   ),
--   '{ce23RealThreshold}', '0.80'::jsonb, true
-- )
-- WHERE id IN ('<PROJECT_ID>')
-- RETURNING id, "settingsJson";
