import { PrismaService } from '../prisma/prisma.service';
import { AuditLogService } from '../audit-log/audit-log.service';
import { EngineRegistry } from '../engine/engine-registry.service';
import { EngineConfigStoreService } from '../engine/engine-config-store.service';
import { JobEngineBindingService } from './job-engine-binding.service';
import { BillingService } from '../billing/billing.service';
import { CapacityGateService } from '../capacity/capacity-gate.service';
import { BudgetService } from '../billing/budget.service';
import { FeatureFlagService } from '../feature-flag/feature-flag.service';
import { TextSafetyService } from '../text-safety/text-safety.service';
import { PublishedVideoService } from '../publish/published-video.service';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { FinancialSettlementService } from '../billing/financial-settlement.service';
import { JobAuthOpsService } from './job-auth-ops.service';
import { CreateJobDto } from './dto/create-job.dto';
import { TaskService } from '../task/task.service';
import { ProjectResolver } from '../common/project-resolver';
export declare class JobCreationOpsService {
    private readonly prisma;
    private readonly auditLogService;
    private readonly engineRegistry;
    private readonly engineConfigStore;
    private readonly jobEngineBindingService;
    private readonly billingService;
    private readonly budgetService;
    private readonly capacityGateService;
    private readonly featureFlagService;
    private readonly textSafetyService;
    private readonly publishedVideoService;
    private readonly eventEmitter;
    private readonly financialSettlementService;
    private readonly taskService;
    private readonly projectResolver;
    private readonly jobAuthOps;
    private readonly logger;
    constructor(prisma: PrismaService, auditLogService: AuditLogService, engineRegistry: EngineRegistry, engineConfigStore: EngineConfigStoreService, jobEngineBindingService: JobEngineBindingService, billingService: BillingService, budgetService: BudgetService, capacityGateService: CapacityGateService, featureFlagService: FeatureFlagService, textSafetyService: TextSafetyService, publishedVideoService: PublishedVideoService, eventEmitter: EventEmitter2, financialSettlementService: FinancialSettlementService, taskService: TaskService, projectResolver: ProjectResolver, jobAuthOps: JobAuthOpsService);
    create(shotId: string, createJobDto: CreateJobDto, userId: string, organizationId: string, taskId?: string): Promise<{
        id: string;
        createdAt: Date;
        payload: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        result: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    validateReferenceSheetId(referenceSheetId: string | undefined, organizationId: string, projectId: string, isVerification?: boolean): Promise<void>;
}
