import { PrismaService } from '../prisma/prisma.service';
import { AuditLogService } from '../audit-log/audit-log.service';
import { TaskService } from '../task/task.service';
import { BillingService } from '../billing/billing.service';
import { CopyrightService } from '../copyright/copyright.service';
import { EventEmitter2 } from '@nestjs/event-emitter';
export declare class JobUpdateOpsService {
    private readonly prisma;
    private readonly auditLogService;
    private readonly taskService;
    private readonly billingService;
    private readonly copyrightService;
    private readonly eventEmitter;
    private readonly logger;
    constructor(prisma: PrismaService, auditLogService: AuditLogService, taskService: TaskService, billingService: BillingService, copyrightService: CopyrightService, eventEmitter: EventEmitter2);
    ackJob(jobId: string, workerId: string): Promise<{
        status: string;
        idempotent: boolean;
    }>;
    reportJobResult(jobId: string, result: {
        status: 'SUCCEEDED' | 'FAILED';
        result?: any;
        errorMessage?: string;
    }, userId?: string): Promise<{
        id: string;
        createdAt: Date;
        payload: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        result: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    completeJob(jobId: string, workerId: string, params: {
        status: 'SUCCEEDED' | 'FAILED';
        result?: any;
        errorMessage?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        payload: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        result: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    updateTaskStatusIfAllJobsCompleted(taskId: string): Promise<void>;
    markJobFailedAndMaybeRetry(jobId: string, errorMessage?: string, userId?: string): Promise<{
        id: string;
        createdAt: Date;
        payload: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        result: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    } | null>;
}
