import { PrismaService } from '../prisma/prisma.service';
import { TaskService } from '../task/task.service';
import { AuditLogService } from '../audit-log/audit-log.service';
import { ProjectResolver } from '../common/project-resolver';
import { CreateJobDto } from './dto/create-job.dto';
import { EngineRegistry } from '../engine/engine-registry.service';
import { QualityScoreService } from '../quality/quality-score.service';
import { EngineConfigStoreService } from '../engine/engine-config-store.service';
import { JobEngineBindingService } from './job-engine-binding.service';
import { BillingService } from '../billing/billing.service';
import { FinancialSettlementService } from '../billing/financial-settlement.service';
import { CopyrightService } from '../copyright/copyright.service';
import { CapacityGateService } from '../capacity/capacity-gate.service';
import { BudgetService } from '../billing/budget.service';
import { FeatureFlagService } from '../feature-flag/feature-flag.service';
import { TextSafetyService } from '../text-safety/text-safety.service';
import { PublishedVideoService } from '../publish/published-video.service';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { Prisma, JobStatus, JobType, TaskStatus, TaskType } from 'database';
export type JobStatusType = JobStatus;
export type JobTypeType = JobType;
export type TaskStatusType = TaskStatus;
export type TaskTypeType = TaskType;
export declare const JobStatusEnum: {
    PENDING: "PENDING";
    RUNNING: "RUNNING";
    SUCCEEDED: "SUCCEEDED";
    FAILED: "FAILED";
    RETRYING: "RETRYING";
    DISPATCHED: "DISPATCHED";
};
export declare const JobTypeEnum: {
    SHOT_RENDER: "SHOT_RENDER";
    NOVEL_ANALYSIS: "NOVEL_ANALYSIS";
    CE06_NOVEL_PARSING: "CE06_NOVEL_PARSING";
    NOVEL_SCAN_TOC: "NOVEL_SCAN_TOC";
    NOVEL_CHUNK_PARSE: "NOVEL_CHUNK_PARSE";
    NOVEL_REDUCE_AGGREGATE: "NOVEL_REDUCE_AGGREGATE";
    CE02_VISUAL_DENSITY: "CE02_VISUAL_DENSITY";
    CE03_VISUAL_DENSITY: "CE03_VISUAL_DENSITY";
    CE04_VISUAL_ENRICHMENT: "CE04_VISUAL_ENRICHMENT";
    CE01_REFERENCE_SHEET: "CE01_REFERENCE_SHEET";
    CE02_IDENTITY_LOCK: "CE02_IDENTITY_LOCK";
    CE05_DIRECTOR_CONTROL: "CE05_DIRECTOR_CONTROL";
    CE07_STORY_MEMORY: "CE07_STORY_MEMORY";
    CE07_MEMORY_UPDATE: "CE07_MEMORY_UPDATE";
    CE08_STORY_KG: "CE08_STORY_KG";
    CE09_MEDIA_SECURITY: "CE09_MEDIA_SECURITY";
    VIDEO_RENDER: "VIDEO_RENDER";
    PIPELINE_E2E_VIDEO: "PIPELINE_E2E_VIDEO";
    PIPELINE_STAGE1_NOVEL_TO_VIDEO: "PIPELINE_STAGE1_NOVEL_TO_VIDEO";
    PIPELINE_TIMELINE_COMPOSE: "PIPELINE_TIMELINE_COMPOSE";
    TIMELINE_RENDER: "TIMELINE_RENDER";
    TIMELINE_PREVIEW: "TIMELINE_PREVIEW";
    EPISODE_RENDER: "EPISODE_RENDER";
    PIPELINE_PROD_VIDEO_V1: "PIPELINE_PROD_VIDEO_V1";
    CE11_SHOT_GENERATOR: "CE11_SHOT_GENERATOR";
    CE06_SCRIPT_OUTLINE: "CE06_SCRIPT_OUTLINE";
    CE11_SCENE_SPLIT: "CE11_SCENE_SPLIT";
    CE12_SHOT_SPLIT: "CE12_SHOT_SPLIT";
    CE13_CHARACTER_CARDS: "CE13_CHARACTER_CARDS";
    CE14_ASSET_LIST: "CE14_ASSET_LIST";
    CE99_CONTINUITY_AUDIT: "CE99_CONTINUITY_AUDIT";
    AUDIO: "AUDIO";
    VG_RENDER: "VG_RENDER";
    AU_RENDER: "AU_RENDER";
    PP_RENDER: "PP_RENDER";
    QC_CHECK: "QC_CHECK";
};
export declare const TaskStatusEnum: {
    PENDING: "PENDING";
    RUNNING: "RUNNING";
    SUCCEEDED: "SUCCEEDED";
    FAILED: "FAILED";
    RETRYING: "RETRYING";
};
export declare const TaskTypeEnum: {
    NOVEL_IMPORT: "NOVEL_IMPORT";
    NOVEL_ANALYSIS: "NOVEL_ANALYSIS";
    SHOT_RENDER: "SHOT_RENDER";
    CE_CORE_PIPELINE: "CE_CORE_PIPELINE";
    VIDEO_RENDER: "VIDEO_RENDER";
    PIPELINE_TIMELINE_COMPOSE: "PIPELINE_TIMELINE_COMPOSE";
    TIMELINE_RENDER: "TIMELINE_RENDER";
    PIPELINE_E2E_VIDEO: "PIPELINE_E2E_VIDEO";
};
import { JobAuthOpsService } from './job-auth-ops.service';
import { JobCreationOpsService } from './job-creation-ops.service';
import { JobUpdateOpsService } from './job-update-ops.service';
export declare class JobService {
    private readonly prisma;
    private readonly taskService;
    private readonly auditLogService;
    private readonly engineRegistry;
    private readonly qualityScoreService;
    private readonly engineConfigStore;
    private readonly jobEngineBindingService;
    private readonly billingService;
    private readonly copyrightService;
    private readonly capacityGateService;
    private readonly featureFlagService;
    private readonly textSafetyService;
    private readonly budgetService;
    private readonly publishedVideoService;
    private readonly eventEmitter;
    private readonly financialSettlementService;
    private readonly projectResolver;
    private readonly jobAuthOps;
    private readonly jobCreationOps;
    private readonly jobUpdateOps;
    private readonly logger;
    constructor(prisma: PrismaService, taskService: TaskService, auditLogService: AuditLogService, engineRegistry: EngineRegistry, qualityScoreService: QualityScoreService, engineConfigStore: EngineConfigStoreService, jobEngineBindingService: JobEngineBindingService, billingService: BillingService, copyrightService: CopyrightService, capacityGateService: CapacityGateService, featureFlagService: FeatureFlagService, textSafetyService: TextSafetyService, budgetService: BudgetService, publishedVideoService: PublishedVideoService, eventEmitter: EventEmitter2, financialSettlementService: FinancialSettlementService, projectResolver: ProjectResolver, jobAuthOps: JobAuthOpsService, jobCreationOps: JobCreationOpsService, jobUpdateOps: JobUpdateOpsService);
    checkShotOwnership(shotId: string, userId: string, organizationId: string): Promise<{
        scene: {
            episode: ({
                project: {
                    id: string;
                    createdAt: Date;
                    name: string;
                    description: string | null;
                    status: import("database").$Enums.ProjectStatus;
                    updatedAt: Date;
                    ownerId: string;
                    organizationId: string;
                    metadata: Prisma.JsonValue | null;
                    settingsJson: Prisma.JsonValue | null;
                    styleGuide: string | null;
                    stylePrompt: string | null;
                } | null;
                season: ({
                    project: {
                        id: string;
                        createdAt: Date;
                        name: string;
                        description: string | null;
                        status: import("database").$Enums.ProjectStatus;
                        updatedAt: Date;
                        ownerId: string;
                        organizationId: string;
                        metadata: Prisma.JsonValue | null;
                        settingsJson: Prisma.JsonValue | null;
                        styleGuide: string | null;
                        stylePrompt: string | null;
                    };
                } & {
                    id: string;
                    createdAt: Date;
                    description: string | null;
                    updatedAt: Date;
                    projectId: string;
                    metadata: Prisma.JsonValue | null;
                    index: number;
                    title: string;
                }) | null;
            } & {
                id: string;
                name: string;
                status: string | null;
                projectId: string | null;
                summary: string | null;
                index: number;
                seasonId: string | null;
                buildId: string | null;
                sourceRefId: string | null;
                chapterId: string | null;
            }) | null;
        } & {
            id: string;
            createdAt: Date;
            status: string | null;
            updatedAt: Date;
            projectId: string | null;
            summary: string | null;
            episodeId: string | null;
            title: string | null;
            characters: Prisma.JsonValue | null;
            reviewStatus: import("database").$Enums.ShotReviewStatus;
            sceneIndex: number;
            buildId: string | null;
            sourceRefId: string | null;
            chapterId: string | null;
            visualDensityScore: Prisma.Decimal | null;
            visualDensityMeta: Prisma.JsonValue | null;
            locationSlug: string | null;
            timeOfDay: string | null;
            environmentTags: string[];
            enrichedText: string | null;
            graphStateSnapshot: Prisma.JsonValue | null;
            sceneDraftId: string | null;
            directingNotes: string | null;
            shotType: string | null;
            characterIds: Prisma.JsonValue | null;
            entryStateJson: Prisma.JsonValue | null;
            exitStateJson: Prisma.JsonValue | null;
        };
    } & {
        params: Prisma.JsonValue;
        qualityScore: Prisma.JsonValue;
        id: string;
        type: string;
        description: string | null;
        organizationId: string | null;
        sceneId: string;
        index: number;
        title: string | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        buildId: string | null;
        sourceRefId: string | null;
        shotType: string | null;
        content: string | null;
        visualDescription: string | null;
        reviewedAt: Date | null;
        durationSeconds: number | null;
        enrichedPrompt: string | null;
        cameraMovement: string | null;
        cameraAngle: string | null;
        lightingPreset: string | null;
        renderStatus: import("database").$Enums.ShotRenderStatus;
        resultImageUrl: string | null;
        resultVideoUrl: string | null;
        visualPrompt: string | null;
        negativePrompt: string | null;
        actionDescription: string | null;
        dialogueContent: string | null;
        soundFx: string | null;
        assetBindings: Prisma.JsonValue | null;
        controlnetSettings: Prisma.JsonValue | null;
        durationSec: Prisma.Decimal | null;
        emotion: string | null;
        novelQuote: string | null;
        continuityJson: Prisma.JsonValue | null;
    }>;
    create(shotId: string, createJobDto: CreateJobDto, userId: string, organizationId: string, taskId?: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    ackJob(jobId: string, workerId: string): Promise<{
        status: string;
        idempotent: boolean;
    }>;
    reportJobResult(jobId: string, status: JobStatusType, result?: any, errorMessage?: string, userId?: string, apiKeyId?: string, ip?: string, userAgent?: string, hmacMeta?: {
        nonce?: string;
        signature?: string;
        hmacTimestamp?: string;
    }, attempts?: number): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    markJobFailedAndMaybeRetry(jobId: string, errorMessage?: string, userId?: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    } | null>;
    completeJob(jobId: string, workerId: string, params: {
        status: 'SUCCEEDED' | 'FAILED';
        result?: any;
        errorMessage?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    validateReferenceSheetId(referenceSheetId: string | undefined, organizationId: string, projectId: string, isVerification?: boolean): Promise<void>;
    createNovelAnalysisJob(createJobDto: CreateJobDto, userId: string, organizationId: string, taskId: string, apiKeyId?: string, ip?: string, userAgent?: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    createCECoreJob(params: {
        projectId: string;
        organizationId: string;
        taskId?: string;
        jobType: JobTypeType;
        payload: any;
        traceId?: string;
        isVerification?: boolean;
        dedupeKey?: string;
        priority?: number;
    }): Promise<any>;
    createCharacterReferenceSheetJob(params: {
        characterId: string;
        organizationId: string;
        projectId: string;
        posePreset?: string;
        styleSeed?: string;
        userId: string;
        traceId?: string;
    }): Promise<{
        referenceSheetId: string;
        engineKey: string;
        engineVersion: string;
        fingerprint: string;
    }>;
    ensureVideoRenderJob(shotId: string, frameKeys: string[], traceId: string, userId: string, organizationId: string, isVerification?: boolean): Promise<any>;
    getAndMarkNextPendingJob(workerId: string, jobType?: string): Promise<any | null>;
    processJob(jobId: string): Promise<void>;
    findByShotId(shotId: string, userId: string, organizationId: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }[]>;
    findJobById(id: string, userId: string, organizationId: string): Promise<{
        shot: ({
            scene: {
                episode: ({
                    season: ({
                        project: {
                            id: string;
                            createdAt: Date;
                            name: string;
                            description: string | null;
                            status: import("database").$Enums.ProjectStatus;
                            updatedAt: Date;
                            ownerId: string;
                            organizationId: string;
                            metadata: Prisma.JsonValue | null;
                            settingsJson: Prisma.JsonValue | null;
                            styleGuide: string | null;
                            stylePrompt: string | null;
                        };
                    } & {
                        id: string;
                        createdAt: Date;
                        description: string | null;
                        updatedAt: Date;
                        projectId: string;
                        metadata: Prisma.JsonValue | null;
                        index: number;
                        title: string;
                    }) | null;
                } & {
                    id: string;
                    name: string;
                    status: string | null;
                    projectId: string | null;
                    summary: string | null;
                    index: number;
                    seasonId: string | null;
                    buildId: string | null;
                    sourceRefId: string | null;
                    chapterId: string | null;
                }) | null;
            } & {
                id: string;
                createdAt: Date;
                status: string | null;
                updatedAt: Date;
                projectId: string | null;
                summary: string | null;
                episodeId: string | null;
                title: string | null;
                characters: Prisma.JsonValue | null;
                reviewStatus: import("database").$Enums.ShotReviewStatus;
                sceneIndex: number;
                buildId: string | null;
                sourceRefId: string | null;
                chapterId: string | null;
                visualDensityScore: Prisma.Decimal | null;
                visualDensityMeta: Prisma.JsonValue | null;
                locationSlug: string | null;
                timeOfDay: string | null;
                environmentTags: string[];
                enrichedText: string | null;
                graphStateSnapshot: Prisma.JsonValue | null;
                sceneDraftId: string | null;
                directingNotes: string | null;
                shotType: string | null;
                characterIds: Prisma.JsonValue | null;
                entryStateJson: Prisma.JsonValue | null;
                exitStateJson: Prisma.JsonValue | null;
            };
        } & {
            params: Prisma.JsonValue;
            qualityScore: Prisma.JsonValue;
            id: string;
            type: string;
            description: string | null;
            organizationId: string | null;
            sceneId: string;
            index: number;
            title: string | null;
            reviewStatus: import("database").$Enums.ShotReviewStatus;
            buildId: string | null;
            sourceRefId: string | null;
            shotType: string | null;
            content: string | null;
            visualDescription: string | null;
            reviewedAt: Date | null;
            durationSeconds: number | null;
            enrichedPrompt: string | null;
            cameraMovement: string | null;
            cameraAngle: string | null;
            lightingPreset: string | null;
            renderStatus: import("database").$Enums.ShotRenderStatus;
            resultImageUrl: string | null;
            resultVideoUrl: string | null;
            visualPrompt: string | null;
            negativePrompt: string | null;
            actionDescription: string | null;
            dialogueContent: string | null;
            soundFx: string | null;
            assetBindings: Prisma.JsonValue | null;
            controlnetSettings: Prisma.JsonValue | null;
            durationSec: Prisma.Decimal | null;
            emotion: string | null;
            novelQuote: string | null;
            continuityJson: Prisma.JsonValue | null;
        }) | null;
        task: {
            error: string | null;
            id: string;
            createdAt: Date;
            payload: Prisma.JsonValue | null;
            type: import("database").$Enums.TaskType;
            status: import("database").$Enums.TaskStatus;
            updatedAt: Date;
            projectId: string;
            organizationId: string;
            traceId: string | null;
            workerId: string | null;
            maxRetry: number;
            retryCount: number;
            attempts: number;
            isVerification: boolean;
            dedupeKey: string | null;
            currentStep: string | null;
            output: Prisma.JsonValue | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    listJobs(userId: string, organizationId: string, filters: {
        status?: string;
        type?: string;
        shotId?: string;
        projectId?: string;
        engineKey?: string;
        from?: string;
        to?: string;
        page?: number;
        pageSize?: number;
    }): Promise<{
        jobs: {
            id: any;
            type: any;
            status: any;
            priority: any;
            attempts: any;
            maxRetry: any;
            retryCount: any;
            createdAt: any;
            updatedAt: any;
            lastError: any;
            shotId: any;
            shotTitle: any;
            projectName: any;
            engineKey: string;
            engineVersion: string | null;
            adapterName: string;
            qualityScore: {
                score: number | null;
                confidence: number | null;
            } | null;
        }[];
        total: number;
        page: number;
        pageSize: number;
        totalPages: number;
    }>;
    extractEngineKeyFromJob(job: {
        type: string;
        payload?: any;
    }): string;
    extractEngineVersionFromJob(job: {
        payload?: any;
        engineConfig?: any;
    }): string | null;
    getEngineSummary(engineKey: string, projectId: string | undefined, userId: string, organizationId: string): Promise<{
        engineKey: string;
        totalJobs: number;
        avgScore: number | null;
        avgConfidence: number | null;
        successRate: number;
        avgDurationMs: number | null;
        avgCostUsd: number | null;
    }>;
    retryJob(jobId: string, userId: string, organizationId: string, resetAttempts?: boolean): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    cancelJob(jobId: string, userId: string, organizationId: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    forceFailJob(jobId: string, userId: string, organizationId: string, message?: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    batchRetry(jobIds: string[], userId: string, organizationId: string, resetAttempts?: boolean): Promise<{
        succeeded: number;
        failed: number;
        total: number;
    }>;
    batchCancel(jobIds: string[], userId: string, organizationId: string): Promise<{
        succeeded: number;
        failed: number;
        total: number;
    }>;
    batchForceFail(jobIds: string[], userId: string, organizationId: string, message?: string): Promise<{
        succeeded: number;
        failed: number;
        total: number;
    }>;
    getNextPendingJobForWorker(workerId: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    } | null>;
    markJobRunning(jobId: string, workerId: string): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    markJobSucceeded(jobId: string, resultPayload?: any): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    markJobFailed(jobId: string, errorMessage?: string, resultPayload?: any): Promise<{
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue | null;
        result: Prisma.JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: Prisma.JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    }>;
    private handleCECoreJobCompletion;
    private handleShotRenderSecurityPipeline;
    private handleCECoreJobFailure;
    getQueueSnapshot(): Promise<{
        pending: number;
        running: number;
        timestamp: string;
    }>;
    private handleStage1ShotCompletion;
    private triggerStage1PipelineAssemble;
    private handleStage1VideoCompletion;
    private triggerQualityHookAfterPersist;
}
