// 审计事件枚举（固定，不得写自由字符串）
export const AuditActions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',
  EPISODE_CREATE: 'EPISODE_CREATE',
  EPISODE_UPDATE: 'EPISODE_UPDATE',
  EPISODE_DELETE: 'EPISODE_DELETE',
  SCENE_CREATE: 'SCENE_CREATE',
  SCENE_UPDATE: 'SCENE_UPDATE',
  SCENE_DELETE: 'SCENE_DELETE',
  SHOT_CREATE: 'SHOT_CREATE',
  SHOT_UPDATE: 'SHOT_UPDATE',
  SHOT_DELETE: 'SHOT_DELETE',
  JOB_CREATE: 'JOB_CREATE',
  JOB_CREATED: 'JOB_CREATED', // Job 创建（与 JOB_CREATE 保持一致）
  JOB_SUCCEEDED: 'JOB_SUCCEEDED', // Job 成功
  JOB_FAILED: 'JOB_FAILED', // Job 失败
  JOB_RETRYING: 'JOB_RETRYING', // Job 重试
  JOB_REPORT: 'JOB_REPORT',
  JOB_STARTED: 'JOB_STARTED', // Job 开始执行
  PERMISSION_UPDATE: 'PERMISSION_UPDATE', // 权限更新（通用）
  SECURITY_EVENT: 'SECURITY_EVENT',
  // S1-FIX-B: 组织切换审计
  ORGANIZATION_SWITCH: 'ORGANIZATION_SWITCH',
  // S1-FIX-B: 权限变更审计
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  ROLE_PERMISSION_GRANT: 'ROLE_PERMISSION_GRANT',
  ROLE_PERMISSION_REVOKE: 'ROLE_PERMISSION_REVOKE',
  // CE04 前置安全检测
  SAFETY_CHECK: 'SAFETY_CHECK',
  // CE09 Asset 相关
  ASSET_ACCESS: 'ASSET_ACCESS',
  ASSET_WATERMARK: 'ASSET_WATERMARK',
  // CE07/CE08 Memory 相关
  MEMORY_ACCESS: 'MEMORY_ACCESS',
  MEMORY_UPDATE: 'MEMORY_UPDATE',
  // CE05 Shot Director 相关
  SHOT_INPAINT: 'SHOT_INPAINT',
  SHOT_POSE: 'SHOT_POSE',
  // Stage2-B: Worker 超时回收
  WORKER_DEAD_RECOVERY: 'WORKER_DEAD_RECOVERY',
  // Stage2-D: Job 回报接收
  JOB_REPORT_RECEIVED: 'JOB_REPORT_RECEIVED',
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];
