import { Prisma } from 'database';
import { PrismaService } from '../prisma/prisma.service';
import { CreateProjectDto, UpdateProjectDto, CreateEpisodeDto, CreateSceneDto, UpdateSceneDto, CreateShotDto, UpdateShotDto } from './dto';
import { SceneGraphService } from './scene-graph.service';
import { AuditLogService } from '../audit-log/audit-log.service';
import { ProjectOverviewDTO } from '@scu/shared-types';
import { ProjectResolver } from '../common/project-resolver';
export declare class ProjectService {
    private readonly prisma;
    private readonly sceneGraphService;
    private readonly auditLogService;
    private readonly projectResolver;
    private readonly logger;
    constructor(prisma: PrismaService, sceneGraphService: SceneGraphService, auditLogService: AuditLogService, projectResolver: ProjectResolver);
    create(createProjectDto: CreateProjectDto, ownerId: string, organizationId: string): Promise<any>;
    findByIdWithHierarchy(id: string, organizationId: string): Promise<any>;
    findTreeById(id: string, organizationId: string): Promise<{
        seasons: any[];
        episodes: any[];
        analysisStatus: "FAILED" | "PENDING" | "DONE" | "ANALYZING";
        analysisUpdatedAt: Date | null;
        sourceType: "DEMO" | "NOVEL";
        productionStatus: "RUNNING" | "DONE" | "READY" | "IDLE";
        structureStatus: "READY" | "EMPTY";
        novelSources: {
            id: string;
            createdAt: Date;
            status: string | null;
            updatedAt: Date;
            projectId: string;
            organizationId: string | null;
            metadata: Prisma.JsonValue | null;
            title: string;
            author: string | null;
            rawFileUrl: string | null;
            totalTokens: bigint | null;
            fileName: string | null;
            fileSize: number | null;
            fileType: string | null;
            characterCount: number | null;
            chapterCount: number | null;
        } | null;
        id: string;
        createdAt: Date;
        name: string;
        description: string | null;
        status: import("database").$Enums.ProjectStatus;
        updatedAt: Date;
        ownerId: string;
        organizationId: string;
        metadata: Prisma.JsonValue | null;
        settingsJson: Prisma.JsonValue | null;
        styleGuide: string | null;
        stylePrompt: string | null;
    }>;
    findAll(userId: string, organizationId: string, page?: number, pageSize?: number): Promise<{
        projects: {
            id: string;
            createdAt: Date;
            name: string;
            description: string | null;
            status: import("database").$Enums.ProjectStatus;
            updatedAt: Date;
        }[];
        total: number;
        page: number;
        pageSize: number;
        totalPages: number;
    }>;
    findById(id: string): Promise<any>;
    update(id: string, updateProjectDto: UpdateProjectDto): Promise<any>;
    delete(id: string): Promise<any>;
    checkOwnership(projectId: string, userId: string): Promise<any>;
    createSeason(projectId: string, createSeasonDto: {
        index: number;
        title: string;
        description?: string;
        metadata?: any;
    }): Promise<{
        id: string;
        createdAt: Date;
        description: string | null;
        updatedAt: Date;
        projectId: string;
        metadata: Prisma.JsonValue | null;
        index: number;
        title: string;
    }>;
    createEpisode(projectIdOrSeasonId: string, createEpisodeDto: CreateEpisodeDto, options?: {
        isSeasonId?: boolean;
    }): Promise<{
        id: string;
        name: string;
        status: string | null;
        projectId: string | null;
        summary: string | null;
        index: number;
        seasonId: string | null;
        buildId: string | null;
        sourceRefId: string | null;
        chapterId: string | null;
    }>;
    checkEpisodeOwnership(episodeId: string, userId: string): Promise<{
        project: {
            id: string;
            createdAt: Date;
            name: string;
            description: string | null;
            status: import("database").$Enums.ProjectStatus;
            updatedAt: Date;
            ownerId: string;
            organizationId: string;
            metadata: Prisma.JsonValue | null;
            settingsJson: Prisma.JsonValue | null;
            styleGuide: string | null;
            stylePrompt: string | null;
        } | null;
    } & {
        id: string;
        name: string;
        status: string | null;
        projectId: string | null;
        summary: string | null;
        index: number;
        seasonId: string | null;
        buildId: string | null;
        sourceRefId: string | null;
        chapterId: string | null;
    }>;
    createScene(episodeId: string, createSceneDto: CreateSceneDto): Promise<{
        id: string;
        createdAt: Date;
        status: string | null;
        updatedAt: Date;
        projectId: string | null;
        summary: string | null;
        episodeId: string | null;
        title: string | null;
        characters: Prisma.JsonValue | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        sceneIndex: number;
        buildId: string | null;
        sourceRefId: string | null;
        chapterId: string | null;
        visualDensityScore: Prisma.Decimal | null;
        visualDensityMeta: Prisma.JsonValue | null;
        locationSlug: string | null;
        timeOfDay: string | null;
        environmentTags: string[];
        enrichedText: string | null;
        graphStateSnapshot: Prisma.JsonValue | null;
        sceneDraftId: string | null;
        directingNotes: string | null;
        shotType: string | null;
        characterIds: Prisma.JsonValue | null;
        entryStateJson: Prisma.JsonValue | null;
        exitStateJson: Prisma.JsonValue | null;
    }>;
    checkSceneOwnership(sceneId: string, userId: string): Promise<{
        episode: ({
            project: {
                id: string;
                createdAt: Date;
                name: string;
                description: string | null;
                status: import("database").$Enums.ProjectStatus;
                updatedAt: Date;
                ownerId: string;
                organizationId: string;
                metadata: Prisma.JsonValue | null;
                settingsJson: Prisma.JsonValue | null;
                styleGuide: string | null;
                stylePrompt: string | null;
            } | null;
        } & {
            id: string;
            name: string;
            status: string | null;
            projectId: string | null;
            summary: string | null;
            index: number;
            seasonId: string | null;
            buildId: string | null;
            sourceRefId: string | null;
            chapterId: string | null;
        }) | null;
    } & {
        id: string;
        createdAt: Date;
        status: string | null;
        updatedAt: Date;
        projectId: string | null;
        summary: string | null;
        episodeId: string | null;
        title: string | null;
        characters: Prisma.JsonValue | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        sceneIndex: number;
        buildId: string | null;
        sourceRefId: string | null;
        chapterId: string | null;
        visualDensityScore: Prisma.Decimal | null;
        visualDensityMeta: Prisma.JsonValue | null;
        locationSlug: string | null;
        timeOfDay: string | null;
        environmentTags: string[];
        enrichedText: string | null;
        graphStateSnapshot: Prisma.JsonValue | null;
        sceneDraftId: string | null;
        directingNotes: string | null;
        shotType: string | null;
        characterIds: Prisma.JsonValue | null;
        entryStateJson: Prisma.JsonValue | null;
        exitStateJson: Prisma.JsonValue | null;
    }>;
    updateScene(id: string, updateSceneDto: UpdateSceneDto): Promise<{
        id: string;
        createdAt: Date;
        status: string | null;
        updatedAt: Date;
        projectId: string | null;
        summary: string | null;
        episodeId: string | null;
        title: string | null;
        characters: Prisma.JsonValue | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        sceneIndex: number;
        buildId: string | null;
        sourceRefId: string | null;
        chapterId: string | null;
        visualDensityScore: Prisma.Decimal | null;
        visualDensityMeta: Prisma.JsonValue | null;
        locationSlug: string | null;
        timeOfDay: string | null;
        environmentTags: string[];
        enrichedText: string | null;
        graphStateSnapshot: Prisma.JsonValue | null;
        sceneDraftId: string | null;
        directingNotes: string | null;
        shotType: string | null;
        characterIds: Prisma.JsonValue | null;
        entryStateJson: Prisma.JsonValue | null;
        exitStateJson: Prisma.JsonValue | null;
    }>;
    createShot(sceneId: string, createShotDto: CreateShotDto, organizationId?: string): Promise<{
        params: Prisma.JsonValue;
        qualityScore: Prisma.JsonValue;
        id: string;
        type: string;
        description: string | null;
        organizationId: string | null;
        sceneId: string;
        index: number;
        title: string | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        buildId: string | null;
        sourceRefId: string | null;
        shotType: string | null;
        content: string | null;
        visualDescription: string | null;
        reviewedAt: Date | null;
        durationSeconds: number | null;
        enrichedPrompt: string | null;
        cameraMovement: string | null;
        cameraAngle: string | null;
        lightingPreset: string | null;
        renderStatus: import("database").$Enums.ShotRenderStatus;
        resultImageUrl: string | null;
        resultVideoUrl: string | null;
        visualPrompt: string | null;
        negativePrompt: string | null;
        actionDescription: string | null;
        dialogueContent: string | null;
        soundFx: string | null;
        assetBindings: Prisma.JsonValue | null;
        controlnetSettings: Prisma.JsonValue | null;
        durationSec: Prisma.Decimal | null;
        emotion: string | null;
        novelQuote: string | null;
        continuityJson: Prisma.JsonValue | null;
    }>;
    checkShotOwnership(shotId: string, userId: string, organizationId: string): Promise<{
        scene: {
            episode: ({
                project: {
                    id: string;
                    createdAt: Date;
                    name: string;
                    description: string | null;
                    status: import("database").$Enums.ProjectStatus;
                    updatedAt: Date;
                    ownerId: string;
                    organizationId: string;
                    metadata: Prisma.JsonValue | null;
                    settingsJson: Prisma.JsonValue | null;
                    styleGuide: string | null;
                    stylePrompt: string | null;
                } | null;
                season: ({
                    project: {
                        id: string;
                        createdAt: Date;
                        name: string;
                        description: string | null;
                        status: import("database").$Enums.ProjectStatus;
                        updatedAt: Date;
                        ownerId: string;
                        organizationId: string;
                        metadata: Prisma.JsonValue | null;
                        settingsJson: Prisma.JsonValue | null;
                        styleGuide: string | null;
                        stylePrompt: string | null;
                    };
                } & {
                    id: string;
                    createdAt: Date;
                    description: string | null;
                    updatedAt: Date;
                    projectId: string;
                    metadata: Prisma.JsonValue | null;
                    index: number;
                    title: string;
                }) | null;
            } & {
                id: string;
                name: string;
                status: string | null;
                projectId: string | null;
                summary: string | null;
                index: number;
                seasonId: string | null;
                buildId: string | null;
                sourceRefId: string | null;
                chapterId: string | null;
            }) | null;
        } & {
            id: string;
            createdAt: Date;
            status: string | null;
            updatedAt: Date;
            projectId: string | null;
            summary: string | null;
            episodeId: string | null;
            title: string | null;
            characters: Prisma.JsonValue | null;
            reviewStatus: import("database").$Enums.ShotReviewStatus;
            sceneIndex: number;
            buildId: string | null;
            sourceRefId: string | null;
            chapterId: string | null;
            visualDensityScore: Prisma.Decimal | null;
            visualDensityMeta: Prisma.JsonValue | null;
            locationSlug: string | null;
            timeOfDay: string | null;
            environmentTags: string[];
            enrichedText: string | null;
            graphStateSnapshot: Prisma.JsonValue | null;
            sceneDraftId: string | null;
            directingNotes: string | null;
            shotType: string | null;
            characterIds: Prisma.JsonValue | null;
            entryStateJson: Prisma.JsonValue | null;
            exitStateJson: Prisma.JsonValue | null;
        };
    } & {
        params: Prisma.JsonValue;
        qualityScore: Prisma.JsonValue;
        id: string;
        type: string;
        description: string | null;
        organizationId: string | null;
        sceneId: string;
        index: number;
        title: string | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        buildId: string | null;
        sourceRefId: string | null;
        shotType: string | null;
        content: string | null;
        visualDescription: string | null;
        reviewedAt: Date | null;
        durationSeconds: number | null;
        enrichedPrompt: string | null;
        cameraMovement: string | null;
        cameraAngle: string | null;
        lightingPreset: string | null;
        renderStatus: import("database").$Enums.ShotRenderStatus;
        resultImageUrl: string | null;
        resultVideoUrl: string | null;
        visualPrompt: string | null;
        negativePrompt: string | null;
        actionDescription: string | null;
        dialogueContent: string | null;
        soundFx: string | null;
        assetBindings: Prisma.JsonValue | null;
        controlnetSettings: Prisma.JsonValue | null;
        durationSec: Prisma.Decimal | null;
        emotion: string | null;
        novelQuote: string | null;
        continuityJson: Prisma.JsonValue | null;
    }>;
    findShotById(id: string, organizationId: string): Promise<{
        scene: {
            episode: ({
                project: {
                    id: string;
                    createdAt: Date;
                    name: string;
                    description: string | null;
                    status: import("database").$Enums.ProjectStatus;
                    updatedAt: Date;
                    ownerId: string;
                    organizationId: string;
                    metadata: Prisma.JsonValue | null;
                    settingsJson: Prisma.JsonValue | null;
                    styleGuide: string | null;
                    stylePrompt: string | null;
                } | null;
            } & {
                id: string;
                name: string;
                status: string | null;
                projectId: string | null;
                summary: string | null;
                index: number;
                seasonId: string | null;
                buildId: string | null;
                sourceRefId: string | null;
                chapterId: string | null;
            }) | null;
        } & {
            id: string;
            createdAt: Date;
            status: string | null;
            updatedAt: Date;
            projectId: string | null;
            summary: string | null;
            episodeId: string | null;
            title: string | null;
            characters: Prisma.JsonValue | null;
            reviewStatus: import("database").$Enums.ShotReviewStatus;
            sceneIndex: number;
            buildId: string | null;
            sourceRefId: string | null;
            chapterId: string | null;
            visualDensityScore: Prisma.Decimal | null;
            visualDensityMeta: Prisma.JsonValue | null;
            locationSlug: string | null;
            timeOfDay: string | null;
            environmentTags: string[];
            enrichedText: string | null;
            graphStateSnapshot: Prisma.JsonValue | null;
            sceneDraftId: string | null;
            directingNotes: string | null;
            shotType: string | null;
            characterIds: Prisma.JsonValue | null;
            entryStateJson: Prisma.JsonValue | null;
            exitStateJson: Prisma.JsonValue | null;
        };
        qualityScores: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            shotId: string;
            visualDensityScore: number | null;
            consistencyScore: number | null;
            motionScore: number | null;
            clarityScore: number | null;
            aestheticScore: number | null;
            overallScore: number;
            attempt: number;
            verdict: string;
            signals: Prisma.JsonValue | null;
            reworkJobId: string | null;
        }[];
        safetyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            shotId: string;
            reviewStatus: import("database").$Enums.ReviewStatus;
            textScore: number;
            imageScore: number;
            riskLevel: import("database").$Enums.RiskLevel;
        }[];
    } & {
        params: Prisma.JsonValue;
        qualityScore: Prisma.JsonValue;
        id: string;
        type: string;
        description: string | null;
        organizationId: string | null;
        sceneId: string;
        index: number;
        title: string | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        buildId: string | null;
        sourceRefId: string | null;
        shotType: string | null;
        content: string | null;
        visualDescription: string | null;
        reviewedAt: Date | null;
        durationSeconds: number | null;
        enrichedPrompt: string | null;
        cameraMovement: string | null;
        cameraAngle: string | null;
        lightingPreset: string | null;
        renderStatus: import("database").$Enums.ShotRenderStatus;
        resultImageUrl: string | null;
        resultVideoUrl: string | null;
        visualPrompt: string | null;
        negativePrompt: string | null;
        actionDescription: string | null;
        dialogueContent: string | null;
        soundFx: string | null;
        assetBindings: Prisma.JsonValue | null;
        controlnetSettings: Prisma.JsonValue | null;
        durationSec: Prisma.Decimal | null;
        emotion: string | null;
        novelQuote: string | null;
        continuityJson: Prisma.JsonValue | null;
    }>;
    updateShot(id: string, updateShotDto: UpdateShotDto, organizationId: string): Promise<{
        params: Prisma.JsonValue;
        qualityScore: Prisma.JsonValue;
        id: string;
        type: string;
        description: string | null;
        organizationId: string | null;
        sceneId: string;
        index: number;
        title: string | null;
        reviewStatus: import("database").$Enums.ShotReviewStatus;
        buildId: string | null;
        sourceRefId: string | null;
        shotType: string | null;
        content: string | null;
        visualDescription: string | null;
        reviewedAt: Date | null;
        durationSeconds: number | null;
        enrichedPrompt: string | null;
        cameraMovement: string | null;
        cameraAngle: string | null;
        lightingPreset: string | null;
        renderStatus: import("database").$Enums.ShotRenderStatus;
        resultImageUrl: string | null;
        resultVideoUrl: string | null;
        visualPrompt: string | null;
        negativePrompt: string | null;
        actionDescription: string | null;
        dialogueContent: string | null;
        soundFx: string | null;
        assetBindings: Prisma.JsonValue | null;
        controlnetSettings: Prisma.JsonValue | null;
        durationSec: Prisma.Decimal | null;
        emotion: string | null;
        novelQuote: string | null;
        continuityJson: Prisma.JsonValue | null;
    }>;
    listEpisodes(userId: string, organizationId: string, filters: {
        projectId?: string;
        seasonId?: string;
        page?: number;
        pageSize?: number;
    }): Promise<{
        data: {
            id: string;
            name: string;
            projectId: string | null;
            index: number;
            seasonId: string | null;
        }[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    listScenes(userId: string, organizationId: string, filters: {
        projectId?: string;
        episodeId?: string;
        page?: number;
        pageSize?: number;
    }): Promise<{
        data: {
            id: string;
            projectId: string | null;
            episodeId: string | null;
            title: string | null;
            sceneIndex: number;
        }[];
        total: number;
        page: number;
        pageSize: number;
        totalPages: number;
    }>;
    listShots(userId: string, organizationId: string, filters: {
        projectId?: string;
        episodeId?: string;
        sceneId?: string;
        status?: string;
        reviewStatus?: string;
        q?: string;
        page?: number;
        pageSize?: number;
    }): Promise<{
        shots: {
            id: any;
            index: any;
            type: any;
            title: any;
            description: any;
            reviewedAt: any;
            projectId: any;
            projectName: any;
            episodeId: any;
            episodeName: any;
            sceneId: any;
            sceneIndex: any;
        }[];
        total: number;
        page: number;
        pageSize: number;
        totalPages: number;
    }>;
    getProjectOverview(projectId: string, organizationId: string): Promise<ProjectOverviewDTO>;
    createDemoStructure(userId: string, organizationId: string): Promise<{
        projectId: string;
    }>;
}
