import { PrismaService } from '../prisma/prisma.service';
import { AuditLogService } from '../audit-log/audit-log.service';
import { JobService } from '../job/job.service';
import { WorkerStatus } from 'database';
export declare class WorkerService {
    private readonly prisma;
    private readonly auditLogService;
    private readonly jobService;
    private readonly logger;
    constructor(prisma: PrismaService, auditLogService: AuditLogService, jobService: JobService);
    private dispatchHistory;
    private readonly CASCADE_LIMIT;
    private readonly CASCADE_WINDOW;
    registerWorker(workerId: string, name: string, capabilities: any, gpuCount?: number, gpuMemory?: number, gpuType?: string, userId?: string, apiKeyId?: string, ip?: string, userAgent?: string): Promise<{
        id: string;
        createdAt: Date;
        name: string | null;
        status: import("database").$Enums.WorkerStatus;
        updatedAt: Date;
        workerId: string;
        gpuCount: number;
        gpuMemory: number;
        gpuType: string;
        tasksRunning: number;
        temperature: number | null;
        capabilities: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue;
        lastHeartbeat: Date;
    }>;
    heartbeat(workerId: string, status?: WorkerStatus, tasksRunning?: number, temperature?: number, _userId?: string, _apiKeyId?: string, _ip?: string, _userAgent?: string): Promise<{
        id: string;
        createdAt: Date;
        name: string | null;
        status: import("database").$Enums.WorkerStatus;
        updatedAt: Date;
        workerId: string;
        gpuCount: number;
        gpuMemory: number;
        gpuType: string;
        tasksRunning: number;
        temperature: number | null;
        capabilities: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue;
        lastHeartbeat: Date;
    }>;
    getOnlineWorkers(jobType?: string): Promise<any[]>;
    isWorkerOnline(workerId: string): Promise<boolean>;
    getNextDispatchedJob(workerId: string): Promise<any>;
    startJob(jobId: string, workerId: string): Promise<any>;
    markOfflineWorkers(): Promise<number>;
    private determineWorkerState;
    getWorkerMonitorSnapshot(): Promise<{
        total: number;
        online: number;
        offline: number;
        idle: number;
        busy: number;
        workers: {
            id: any;
            status: any;
            capabilities: any;
            isOnline: boolean;
            lastHeartbeat: any;
            tasksRunning: any;
            createdAt: any;
            updatedAt: any;
            currentEngineKey: string | null;
        }[];
    }>;
    evaluateWorkerHealth(workerId: string): Promise<{
        workerId: string;
        status: 'HEALTHY' | 'DEGRADED' | 'DEAD';
        lastSeenSec?: number;
    }>;
    private getDeadWorkerIds;
    reclaimJobsFromDeadWorkers(): Promise<number>;
    dispatchNextJobForWorker(workerId: string): Promise<{
        id: string;
        createdAt: Date;
        payload: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        result: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        type: import("database").$Enums.JobType;
        status: import("database").$Enums.JobStatus;
        updatedAt: Date;
        projectId: string;
        organizationId: string;
        traceId: string | null;
        episodeId: string | null;
        sceneId: string | null;
        shotId: string | null;
        taskId: string | null;
        workerId: string | null;
        priority: number;
        maxRetry: number;
        retryCount: number;
        attempts: number;
        leaseUntil: Date | null;
        lockedBy: string | null;
        engineConfig: import("../../../../packages/database/dist/generated/prisma/runtime/library").JsonValue | null;
        lastError: string | null;
        isVerification: boolean;
        dedupeKey: string | null;
        outputSha256: string | null;
        engineProvider: string | null;
        engineRunId: string | null;
        engineModel: string | null;
        securityProcessed: boolean;
        currentStep: string | null;
    } | null>;
}
