import { OnModuleInit } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';
import { EngineAdapter, EngineInvokeInput, EngineInvokeResult } from '@scu/shared-types';
import { ShotRenderReplicateAdapter } from './shot-render.replicate.adapter';
import { ShotRenderLocalAdapter } from './shot-render.local.adapter';
import { ShotRenderComfyuiAdapter } from './shot-render.comfyui.adapter';
import { ShotRenderMpsAdapter } from './shot-render.mps.adapter';
import { FusionAdapter } from './fusion.adapter';
import { PrismaService } from '../../prisma/prisma.service';
import { VG08AdvancedLightingAdapter } from './vg08_advanced_lighting.adapter';
import { CE13PacingAnalyzerAdapter } from './ce13_pacing_analyzer.adapter';
export declare class ShotRenderRouterAdapter implements EngineAdapter, OnModuleInit {
    private readonly moduleRef;
    private readonly prisma;
    private readonly replicateAdapter;
    private readonly comfyuiAdapter;
    private readonly localAdapter;
    private readonly mpsAdapter;
    private readonly fusionAdapter;
    private readonly lightingAdapter;
    private readonly pacingAdapter;
    readonly name = "shot_render_router";
    private readonly logger;
    private adapters;
    constructor(moduleRef: ModuleRef, prisma: PrismaService, replicateAdapter: ShotRenderReplicateAdapter, comfyuiAdapter: ShotRenderComfyuiAdapter, localAdapter: ShotRenderLocalAdapter, mpsAdapter: ShotRenderMpsAdapter, fusionAdapter: FusionAdapter, lightingAdapter: VG08AdvancedLightingAdapter, pacingAdapter: CE13PacingAnalyzerAdapter);
    private mockAdapter;
    private characterService;
    onModuleInit(): Promise<void>;
    private ensureDependencies;
    supports(engineKey: string): boolean;
    invoke(input: EngineInvokeInput): Promise<EngineInvokeResult>;
    private generateProvenanceKit;
    private calculateSha256;
    private getRepoRoot;
    private selectProvider;
    private getAdapter;
    private coordinateStellarAesthetics;
    private mountCharacterLora;
}
