import { OnModuleInit } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';
import { EngineRegistry } from '../engine/engine-registry.service';
import { NovelAnalysisLocalAdapter } from './adapters/novel-analysis.local.adapter.NEW';
import { CE06LocalAdapter } from './adapters/ce06_novel_parsing.adapter';
import { CE09SecurityLocalAdapter } from './adapters/ce09_security.adapter';
import { CE03LocalAdapter } from './adapters/ce03_visual_density.adapter';
import { CE04LocalAdapter } from './adapters/ce04_visual_enrichment.adapter';
import { VideoMergeLocalAdapter } from './adapters/video_merge.adapter';
import { ShotRenderLocalAdapter } from './adapters/shot-render.local.adapter';
import { ShotRenderReplicateAdapter } from './adapters/shot-render.replicate.adapter';
import { ShotRenderComfyuiAdapter } from './adapters/shot-render.comfyui.adapter';
import { ShotRenderMpsAdapter } from './adapters/shot-render.mps.adapter';
import { ShotRenderRouterAdapter } from './adapters/shot_render_router.adapter';
import { FusionAdapter } from './adapters/fusion.adapter';
import { HttpEngineAdapter } from '../engine/adapters/http-engine.adapter';
import { MockEngineAdapter } from '../engine/adapters/mock-engine.adapter';
import { CE11ComfyUIAdapter } from '../engine/adapters/ce11.comfyui.adapter';
import { TranslationCloudAdapter } from './adapters/translation.cloud.adapter';
import { StyleTransferReplicateAdapter } from './adapters/style-transfer.replicate.adapter';
import { CharacterGenAdapter } from './adapters/character_gen.adapter';
import { SceneCompositionAdapter } from './adapters/scene_composition.adapter';
import { EmotionAnalysisAdapter } from './adapters/emotion_analysis.adapter';
import { DialogueOptimizationAdapter } from './adapters/dialogue_optimization.adapter';
import { CE07MemoryUpdateAdapter } from './adapters/ce07_memory_update.adapter';
import { CE01NarrativeStructureAdapter } from './adapters/ce01_narrative_structure.adapter';
import { CE05ConflictDetectorAdapter } from './adapters/ce05_conflict_detector.adapter';
import { CE08CharacterArcAdapter } from './adapters/ce08_character_arc.adapter';
import { CE12ThemeExtractorAdapter } from './adapters/ce12_theme_extractor.adapter';
import { CE13PacingAnalyzerAdapter } from './adapters/ce13_pacing_analyzer.adapter';
import { Ce14NarrativeClimaxAdapter } from './adapters/ce14_narrative_climax.adapter';
import { CE15MultiCharSceneAdapter } from './adapters/ce15_multi_char_scene.adapter';
import { CE16StoryBranchCoordinatorAdapter } from './adapters/ce16_story_branch_coordinator.adapter';
import { CE17CulturalConsistencyAdapter } from './adapters/ce17_cultural_consistency.adapter';
import { CE18WorldLogicValidatorAdapter } from './adapters/ce18_world_logic_validator.adapter';
import { CE19StorySummaryGenAdapter } from './adapters/ce19_story_summary_gen.adapter';
import { VG01BackgroundRenderAdapter } from './adapters/vg01_background_render.adapter';
import { VG02CharacterRenderAdapter } from './adapters/vg02_character_render.adapter';
import { VG03LightingEngineAdapter } from './adapters/vg03_lighting_engine.adapter';
import { VG04CameraPathAdapter } from './adapters/vg04_camera_path.adapter';
import { VG05VFXCompositorAdapter } from './adapters/vg05_vfx_compositor.adapter';
import { VG06SkeletalAnimationAdapter } from './adapters/vg06_skeletal_animation.adapter';
import { VG07FacialExpressionAdapter } from './adapters/vg07_facial_expression.adapter';
import { VG08AdvancedLightingAdapter } from './adapters/vg08_advanced_lighting.adapter';
import { VG09HairPhysicsAdapter } from './adapters/vg09_hair_physics.adapter';
import { VG10ClothDynamicsAdapter } from './adapters/vg10_cloth_dynamics.adapter';
import { VG11ParticleEffectsAdapter } from './adapters/vg11_particle_effects.adapter';
import { VG12DynamicLightingRigAdapter } from './adapters/vg12_dynamic_lighting_rig.adapter';
import { AU01VoiceTTSAdapter } from './adapters/au01_voice_tts.adapter';
import { AU02BGMGenAdapter } from './adapters/au02_bgm_gen.adapter';
import { AU03SFXGenAdapter } from './adapters/au03_sfx_gen.adapter';
import { AU04AudioMixAdapter } from './adapters/au04_audio_mix.adapter';
import { AU05EnvironmentalReverbAdapter } from './adapters/au05_environmental_reverb.adapter';
import { AU06SpatialAudioAdapter } from './adapters/au06_spatial_audio.adapter';
import { PP01VideoStitchAdapter } from './adapters/pp01_video_stitch.adapter';
import { PP02SubtitleOverlayAdapter } from './adapters/pp02_subtitle_overlay.adapter';
import { PP03WatermarkAdapter } from './adapters/pp03_watermark.adapter';
import { PP04HLSPackageAdapter } from './adapters/pp04_hls_package.adapter';
import { PP05PosterGenAdapter } from './adapters/pp05_poster_gen.adapter';
import { PP06CreditsGenAdapter } from './adapters/pp06_credits_gen.adapter';
import { QC01VisualFidelityAdapter } from './adapters/qc01_visual_fidelity.adapter';
import { QC02NarrativeConsistencyAdapter } from './adapters/qc02_narrative_consistency.adapter';
import { QC03IdentityContinuityAdapter } from './adapters/qc03_identity_continuity.adapter';
import { QC04ComplianceScanAdapter } from './adapters/qc04_compliance_scan.adapter';
import { QC05TechnicalComplianceAdapter } from './adapters/qc05_technical_compliance.adapter';
import { QC06FlickerDetectorAdapter } from './adapters/qc06_flicker_detector.adapter';
import { CE23IdentityLocalAdapter } from './adapters/ce23_identity_lock.adapter';
import { G5DialogueBindingAdapter } from './adapters/g5-dialogue-binding.adapter';
import { G5SemanticMotionMapperAdapter } from './adapters/g5-semantic-motion-mapper.adapter';
import { G5AssetLayeringResolverAdapter } from './adapters/g5-asset-layering-resolver.adapter';
import { AudioTTSLocalAdapter } from './adapters/audio-tts.local.adapter';
export declare class EngineModule implements OnModuleInit {
    private readonly moduleRef;
    private registry;
    private readonly novelAdapter;
    private readonly ce06Adapter;
    private readonly ce03Adapter;
    private readonly ce04Adapter;
    private readonly videoMergeAdapter;
    private readonly shotRenderAdapter;
    private readonly shotRenderReplicateAdapter;
    private readonly shotRenderComfyuiAdapter;
    private readonly shotRenderMpsAdapter;
    private readonly shotRenderRouterAdapter;
    private readonly fusionAdapter;
    private readonly httpAdapter;
    private readonly mockEngineAdapter;
    private readonly ce11ComfyUIAdapter;
    private readonly g5DialogueBindingAdapter;
    private readonly g5SemanticMotionMapperAdapter;
    private readonly g5AssetLayeringResolverAdapter;
    private readonly translationCloudAdapter;
    private readonly styleTransferReplicateAdapter;
    private readonly characterGenAdapter;
    private readonly sceneCompositionAdapter;
    private readonly emotionAnalysisAdapter;
    private readonly dialogueOptimizationAdapter;
    private readonly ce07Adapter;
    private readonly ce01Adapter;
    private readonly ce05Adapter;
    private readonly ce08Adapter;
    private readonly ce12Adapter;
    private readonly ce13Adapter;
    private readonly ce14Adapter;
    private readonly ce15Adapter;
    private readonly ce16Adapter;
    private readonly ce17Adapter;
    private readonly ce09Adapter;
    private readonly ce18Adapter;
    private readonly ce19Adapter;
    private readonly vg01Adapter;
    private readonly vg02Adapter;
    private readonly vg03Adapter;
    private readonly vg04Adapter;
    private readonly vg05Adapter;
    private readonly vg06Adapter;
    private readonly vg07Adapter;
    private readonly vg08Adapter;
    private readonly vg09Adapter;
    private readonly vg10Adapter;
    private readonly vg11Adapter;
    private readonly vg12Adapter;
    private readonly au01Adapter;
    private readonly au02Adapter;
    private readonly au03Adapter;
    private readonly au04Adapter;
    private readonly au05Adapter;
    private readonly au06Adapter;
    private readonly pp01Adapter;
    private readonly pp02Adapter;
    private readonly pp03Adapter;
    private readonly pp04Adapter;
    private readonly pp05Adapter;
    private readonly pp06Adapter;
    private readonly qc01Adapter;
    private readonly qc02Adapter;
    private readonly qc03Adapter;
    private readonly qc04Adapter;
    private readonly qc05Adapter;
    private readonly qc06Adapter;
    private readonly ce23Adapter;
    private readonly audioTTSAdapter;
    private readonly logger;
    constructor(moduleRef: ModuleRef, registry: EngineRegistry, novelAdapter: NovelAnalysisLocalAdapter, ce06Adapter: CE06LocalAdapter, ce03Adapter: CE03LocalAdapter, ce04Adapter: CE04LocalAdapter, videoMergeAdapter: VideoMergeLocalAdapter, shotRenderAdapter: ShotRenderLocalAdapter, shotRenderReplicateAdapter: ShotRenderReplicateAdapter, shotRenderComfyuiAdapter: ShotRenderComfyuiAdapter, shotRenderMpsAdapter: ShotRenderMpsAdapter, shotRenderRouterAdapter: ShotRenderRouterAdapter, fusionAdapter: FusionAdapter, httpAdapter: HttpEngineAdapter, mockEngineAdapter: MockEngineAdapter, ce11ComfyUIAdapter: CE11ComfyUIAdapter, g5DialogueBindingAdapter: G5DialogueBindingAdapter, g5SemanticMotionMapperAdapter: G5SemanticMotionMapperAdapter, g5AssetLayeringResolverAdapter: G5AssetLayeringResolverAdapter, translationCloudAdapter: TranslationCloudAdapter, styleTransferReplicateAdapter: StyleTransferReplicateAdapter, characterGenAdapter: CharacterGenAdapter, sceneCompositionAdapter: SceneCompositionAdapter, emotionAnalysisAdapter: EmotionAnalysisAdapter, dialogueOptimizationAdapter: DialogueOptimizationAdapter, ce07Adapter: CE07MemoryUpdateAdapter, ce01Adapter: CE01NarrativeStructureAdapter, ce05Adapter: CE05ConflictDetectorAdapter, ce08Adapter: CE08CharacterArcAdapter, ce12Adapter: CE12ThemeExtractorAdapter, ce13Adapter: CE13PacingAnalyzerAdapter, ce14Adapter: Ce14NarrativeClimaxAdapter, ce15Adapter: CE15MultiCharSceneAdapter, ce16Adapter: CE16StoryBranchCoordinatorAdapter, ce17Adapter: CE17CulturalConsistencyAdapter, ce09Adapter: CE09SecurityLocalAdapter, ce18Adapter: CE18WorldLogicValidatorAdapter, ce19Adapter: CE19StorySummaryGenAdapter, vg01Adapter: VG01BackgroundRenderAdapter, vg02Adapter: VG02CharacterRenderAdapter, vg03Adapter: VG03LightingEngineAdapter, vg04Adapter: VG04CameraPathAdapter, vg05Adapter: VG05VFXCompositorAdapter, vg06Adapter: VG06SkeletalAnimationAdapter, vg07Adapter: VG07FacialExpressionAdapter, vg08Adapter: VG08AdvancedLightingAdapter, vg09Adapter: VG09HairPhysicsAdapter, vg10Adapter: VG10ClothDynamicsAdapter, vg11Adapter: VG11ParticleEffectsAdapter, vg12Adapter: VG12DynamicLightingRigAdapter, au01Adapter: AU01VoiceTTSAdapter, au02Adapter: AU02BGMGenAdapter, au03Adapter: AU03SFXGenAdapter, au04Adapter: AU04AudioMixAdapter, au05Adapter: AU05EnvironmentalReverbAdapter, au06Adapter: AU06SpatialAudioAdapter, pp01Adapter: PP01VideoStitchAdapter, pp02Adapter: PP02SubtitleOverlayAdapter, pp03Adapter: PP03WatermarkAdapter, pp04Adapter: PP04HLSPackageAdapter, pp05Adapter: PP05PosterGenAdapter, pp06Adapter: PP06CreditsGenAdapter, qc01Adapter: QC01VisualFidelityAdapter, qc02Adapter: QC02NarrativeConsistencyAdapter, qc03Adapter: QC03IdentityContinuityAdapter, qc04Adapter: QC04ComplianceScanAdapter, qc05Adapter: QC05TechnicalComplianceAdapter, qc06Adapter: QC06FlickerDetectorAdapter, ce23Adapter: CE23IdentityLocalAdapter, audioTTSAdapter: AudioTTSLocalAdapter);
    onModuleInit(): void;
}
