#!/bin/bash
# run_p5_final_review.sh: Phase 5 最终审计复核与交付运行器
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TS=$(date +%Y%m%d_%H%M%S)
OUT="$REPO_ROOT/docs/_evidence/p5_final_review_${TS}"
EVI_SRC="docs/_evidence/p5_full_audit_20260131_201038"

mkdir -p "$OUT"
echo "🚀 [FINAL-REVIEW] Starting Phase 5 Final Review -> $OUT"

# --- PLAN-0: 冻结现场 (Env Snapshot) ---
echo "[PHASE-5] Capturing Environment Snapshot..."
{
    echo "--- Git Status ---"
    git rev-parse HEAD
    git status --porcelain
    echo -e "\n--- Versions ---"
    node -v || echo "node not found"
    pnpm -v || echo "pnpm not found"
    python3 --version || echo "python3 not found"
    echo -e "\n--- System ---"
    uname -a
    if [[ "$OSTYPE" == "darwin"* ]]; then
        system_profiler SPHardwareDataType | head -n 30
    fi
} > "$OUT/env_snapshot.txt"

# --- PLAN-1: 证据包完整性与索引自证 ---
echo "[PHASE-5] Verifying Baseline Integrity ($EVI_SRC)..."
if [ -d "$REPO_ROOT/$EVI_SRC" ]; then
    ls -lah "$REPO_ROOT/$EVI_SRC" > "$OUT/baseline_ls.txt"
    if [ -f "$REPO_ROOT/$EVI_SRC/EVIDENCE_INDEX.json" ]; then
        jq . "$REPO_ROOT/$EVI_SRC/EVIDENCE_INDEX.json" >/dev/null && echo "EVIDENCE_INDEX.json: OK"
    fi
    shasum -a 256 "$REPO_ROOT/$EVI_SRC"/* > "$OUT/baseline_SHA256SUMS.txt"
else
    echo "⚠️  WARNING: Baseline evidence directory $EVI_SRC not found!"
fi

# --- PLAN-2: 一键复跑 (Proof of Reproducibility) ---
echo "[PHASE-5] Running One-key Re-run (Reproduce Results)..."
# We create a sub-evidence dir for the re-run within the review dir to avoid pollution
RERUN_EVI="$OUT/rerun_evidence"
mkdir -p "$RERUN_EVI"

# Mock the baseline files for rerun if needed or let the runner handle it
# In our project, run_p5_full_audit.sh handles its own timestamped directory
# We'll point it to use the RERUN_EVI if possible or just let it run and copy results
bash "$REPO_ROOT/tools/run_p5_full_audit.sh" 2>&1 | tee "$OUT/run_p5_full_audit.log" || echo "FAIL" > "$OUT/exit_log.txt"
echo $? > "$OUT/exit_code.txt"

# --- PLAN-3: 三份核心报告的“可审计复核” ---
echo "[PHASE-5] Extracting Audit Snapshots..."
# Find the latest audit dir generated by run_p5_full_audit.sh
LATEST_EVI=$(ls -td "$REPO_ROOT/docs/_evidence/p5_full_audit_"* | head -1)

if [ -n "$LATEST_EVI" ]; then
    cp "$LATEST_EVI/concurrency_perf.json" "$OUT/" || true
    cp "$LATEST_EVI/unit_cost_audit.json" "$OUT/" || true
    cp "$LATEST_EVI/stability_audit.json" "$OUT/" || true
    
    jq . "$LATEST_EVI/concurrency_perf.json" | head -n 120 > "$OUT/concurrency_perf_head.json"
    jq . "$LATEST_EVI/unit_cost_audit.json" | head -n 200 > "$OUT/unit_cost_audit_head.json"
    jq . "$LATEST_EVI/stability_audit.json" | head -n 200 > "$OUT/stability_audit_head.json"
fi

# --- PLAN-4: 封板材料固化 (Index Generation) ---
echo "[PHASE-5] Finalizing Index..."
node "$REPO_ROOT/tools/evidence/gen_evidence_index.mjs" "$OUT"

echo "✅ [FINAL-REVIEW] Phase 5 Final Review Complete."
echo "Review Directory: $OUT"
